/**
 * \@iso4/sandbox — public API types.
 *
 * Execution model: precompile a prefix once into a V8 startup snapshot,
 * then call prefix.run({ code }) for each piece of dynamic code (e.g.
 * agent-generated). A fresh isolate is created from the snapshot per call.
 * Multiple concurrent callers each get their own pool slot and run in
 * parallel. See DESIGN.md §1 and §13.
 */

// ─────────────────────────────────────────────────────────────────────────
// Resource limits
// ─────────────────────────────────────────────────────────────────────────

export interface ResourceLimits {
  /**
   * Hard cap on memory the isolate can use, in megabytes.
   * Covers the V8 heap and all external `ArrayBuffer` allocations.
   *
   * Also determines the BridgeResponse frame read cap: the sandbox cannot
   * receive a response larger than its own memory budget.
   *
   * Zero means no cap.
   * @default 64
   */
  memoryMb: number

  /**
   * Maximum *active* execution time in milliseconds. Time spent waiting on
   * host bridge calls (globals, host imports) is excluded.
   * @default 5_000
   */
  cpuTimeMs: number

  /**
   * Hard wall-clock cap including async waits.
   * @default 30_000
   */
  wallTimeMs: number

  /**
   * Maximum bytes the sandbox may send as arguments in a single bridge call
   * (sandbox → host direction). Protects the host from receiving unexpectedly
   * large payloads generated by untrusted sandbox code.
   *
   * Bridge responses (host → sandbox) are not separately capped here — the
   * natural limit is `memoryMb`: the sandbox cannot hold a response larger than
   * its own memory budget, and the framing layer enforces this automatically.
   *
   * Zero disables the per-call cap.
   * @default 16 * 1024 * 1024
   */
  maxBridgeCallBytes: number

  /**
   * Maximum bytes allowed for the serialised export payload (all named exports
   * combined). Exceeding this limit terminates the run with `ERR_EXPORT_TOO_LARGE`.
   * Zero disables the cap.
   * @default 16 * 1024 * 1024
   */
  maxExportBytes: number

  /**
   * Maximum bytes captured from `console.log` / `console.debug` / `console.info`
   * combined. Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStdoutBytes: number

  /**
   * Maximum bytes captured from `console.warn` / `console.error` combined.
   * Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStderrBytes: number

  /**
   * Maximum number of bridge calls (globals + host imports combined) a
   * single run may make. Zero disables the per-run limit entirely.
   *
   * Protects against untrusted sandbox code making unbounded calls to host
   * handlers (e.g. `while(true) { await myTool() }`) which consumes near-zero
   * CPU budget but can exhaust host resources (network, DB, LLM quota).
   *
   * @default 10
   */
  maxBridgeCalls: number
}

// ─────────────────────────────────────────────────────────────────────────
// Globals (generic bridge — any non-reserved name is permitted)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Host-provided globals. Any name not reserved by V8 or the runtime is
 * permitted. Each value becomes a bridge stub in the sandbox global object.
 *
 * Reserved names (must not be used): `console`, `URL`, `URLSearchParams`,
 * `TextEncoder`, `TextDecoder`, `crypto`, `Event`, `AbortController`,
 * `AbortSignal`.
 *
 * Common usage:
 * ```ts
 * globals: {
 * fetch: myFetchHandler,   // \@iso4/fetch provides createSafeFetch()
 * myTool: async (arg) => doSomething(arg),
 * }
 * ```
 *
 * `fetch` is not special — it goes through the same bridge path as any
 * other entry.
 *
 * Three value shapes are supported — see `HostGlobalValue`.
 */
export type HostGlobals = Record<string, HostGlobalValue>

/**
 * The value types accepted for a named global.
 *
 * - `HostExportFunction` — bridge call: every sandbox invocation dispatches
 *   to the host handler.
 * - `string` — a JS expression installed once at prefix setup:
 *   `globalThis.<name> = <expr>`. Use for pure sandbox utilities that need
 *   no host involvement.
 * - `BridgeWithShim` — bridge call + in-sandbox result wrapper. The handler
 *   can be rebound per `prefix.run()`; the shim is compiled into the snapshot.
 */

export type HostGlobalValue = HostExportFunction | string | BridgeWithShim<any>

/**
 * A global that pairs a bridge handler with an in-sandbox shim that wraps
 * its return value. Typical use: adding `.json()` / `.text()` convenience
 * methods to a fetch response without extra bridge round-trips.
 *
 * The TS layer:
 *  1. Registers `handler` as a bridge stub under `__iso4_<name>_h`.
 *  2. Prepends to the prefix source:
 *     ```js
 *     globalThis.<name> = async (...args) =>
 *       await (<shim>)(await __iso4_<name>_h(...args))
 *     ```
 *
 * The shim is a JS function expression `(result) => transformedResult` (sync
 * or async). Sandbox built-ins (TextDecoder, JSON, …) are available in scope.
 * The private stub `__iso4_<name>_h` stays on globalThis so the handler can
 * be rebound per `prefix.run()` while the shim stays fixed in the snapshot.
 */
/**
 * `H` is the specific handler function type. Carried through the type system
 * so `RebindGlobals` can enforce that any per-run replacement has the same
 * return type, keeping it compatible with the shim that is already compiled
 * into the prefix snapshot.
 */
export interface BridgeWithShim<
  H extends (...args: unknown[]) => unknown = (...args: unknown[]) => unknown,
> {
  kind: 'bridge-with-shim'
  /**
   * Bridge handler — registered as `__iso4_<name>_h` for rebinding.
   */
  handler: H
  /**
   * JS function expression that transforms the bridge return value.
   * Runs in the sandbox. May be async.
   *
   * @example
   * ```ts
   * shim: `(result) => ({
   *   ...result,
   *   ok:   result.status >= 200 && result.status < 300,
   *   json: () => JSON.parse(new TextDecoder().decode(result.body)),
   *   text: () => new TextDecoder().decode(result.body),
   * })`
   * ```
   */
  shim: string
}

/**
 * What can be supplied as a per-run override for a global declared at
 * precompile time:
 *
 * - `BridgeWithShim<H>` global — only the handler `H` itself. The shim is
 *   fixed in the snapshot; rebinding must preserve the return type so the
 *   shim keeps working.
 * - `HostExportFunction` global — any compatible `HostExportFunction`.
 * - `string` global — cannot be rebound (compiled into the snapshot).
 */
export type RebindValue<V extends HostGlobalValue>
  = V extends BridgeWithShim<infer H> ? H
    : V extends HostExportFunction ? V
      : never

/**
 * The per-run globals override map for a `Prefix<G>`.
 *
 * String-valued globals are filtered out entirely (key remapping to `never`)
 * rather than mapped to `?: never` — they cannot be rebound because their
 * expression is compiled into the snapshot, and they should not appear as
 * valid keys at all.
 *
 * Each remaining key is optional and typed as `RebindValue<G[K]>`, which
 * enforces the correct constraint per global kind.
 */
export type RebindGlobals<G extends HostGlobals> = {
  [K in keyof G as G[K] extends string ? never : K]?: RebindValue<G[K]>
}

// ─────────────────────────────────────────────────────────────────────────
// Imports
// ─────────────────────────────────────────────────────────────────────────
//
// `imports` is a flat map keyed by specifier. The value type discriminates:
//
//   string → source module: host provides ESM source. V8 compiles it inside
//     the isolate; transitive `import`s resolve back through the same map.
//     Zero per-call bridge cost.
//
//   object → host module: host provides a JS object describing the module
//     shape. The runtime walks the object recursively and generates ESM
//     source that exposes the structure: function leaves become async
//     stubs that issue bridge calls to a host-side handler, data leaves
//     become JS literals. Nested objects mixing data and functions are
//     supported natively.

/**
 * Top-level `imports` shape. Keys are import specifiers; values are either
 * a source string or a host-module description object.
 *
 * `M` is the literal shape of the map. `precompile()` infers it from the
 * object literal so the declared specifiers and their value shapes flow
 * into `Prefix<G, M>` and feed `RebindImports<M>`.
 */
export type Imports<M extends Record<string, ImportValue> = Record<string, ImportValue>> = M

/**
 * A single import value. String = source module. Object = host module
 * description (the recursive walker handles all nesting).
 */
export type ImportValue = string | HostModuleObject

/**
 * A host-module description object. Each property is either:
 *
 *   - A function — becomes an async bridge stub in the generated module.
 *   - A plain data value (primitive, plain object/array, `Date`, `BigInt`,
 *     `Uint8Array`) — becomes a JS literal in the generated module.
 *   - A nested object that itself contains a mix of functions and data —
 *     walked recursively.
 *
 * `Map`, `Set`, circular references, class instances with prototype
 * methods, and stateful handles (streams, sockets) are rejected at
 * registration with a clear error.
 */
export interface HostModuleObject {
  [name: string]: HostModuleValue
}

/**
 * Any node the recursive walker may encounter inside a `HostModuleObject`.
 */
export type HostModuleValue
  = | HostExportFunction
    | HostExportData
    | HostModuleObject

/**
 * The set of plain-data values supported as data leaves in the host-module
 * shape. The JS-literal emitter knows how to emit each of these.
 */
export type HostExportData
  = | null
    | undefined
    | boolean
    | number
    | bigint
    | string
    | Uint8Array
    | Date
    | HostExportData[]
    | { [key: string]: HostExportData }

/**
 * A host-side function exposed as a global or import-tree leaf.
 *
 * Args and return are `unknown` — the bridge serialises/deserialises values
 * with V8 ValueSerializer; we don't try to model that at the type level.
 * The one invariant that matters (functions cannot cross the boundary as
 * argument values) is enforced at runtime by the V8 layer, not here.
 *
 * Use specific function types for your handlers and let TypeScript infer
 * them through `HostGlobals`, `RebindGlobals<G>`, and `RebindImports<M>`.
 */
export type HostExportFunction = (...args: unknown[]) => unknown

/**
 * The rebindable subset of an `Imports<M>` declared at precompile time.
 *
 * Mirrors `RebindGlobals<G>` over the recursive host-module shape:
 *
 * - **Source imports** (string values) are compiled into the snapshot and
 *   cannot be rebound — their keys are excluded from the result.
 * - **Host imports** (object values) are walked recursively. Only function
 *   leaves survive; data leaves are excluded because their values are
 *   emitted as JS literals into the generated module.
 *
 * Passing a specifier or export name that was not declared at precompile
 * is a TypeScript error at compile time and `ERR_UNDECLARED_BINDING` at
 * runtime.
 *
 * When `M` is left at its wide default (no `imports` declared, or no
 * literal shape inferred), the rebind keyspace collapses to
 * `Record<string, never>` — the walker only kicks in for literal shapes,
 * which have finite depth.
 */
export type RebindImports<M extends Record<string, ImportValue>>
  = Record<string, ImportValue> extends M
    ? Record<string, never>
    : {
        [K in keyof M as M[K] extends string ? never : K]?:
        M[K] extends HostModuleObject ? RebindHostModule<M[K]> : never
      }

/**
 * Recursive walker over a `HostModuleObject`. Function leaves keep
 * their declared signature; nested objects recurse; data leaves drop out
 * entirely. Only used against literal shapes inferred by `precompile`, so
 * the recursion is always finite.
 */
export type RebindHostModule<T> = T extends HostExportFunction
  ? T
  : T extends HostModuleObject
    ? {
        [K in keyof T as T[K] extends HostExportFunction
          ? K
          : T[K] extends HostModuleObject
            ? K
            : never]?: T[K] extends HostExportFunction
          ? T[K]
          : T[K] extends HostModuleObject
            ? RebindHostModule<T[K]>
            : never
      }
    : never

// ─────────────────────────────────────────────────────────────────────────
// Sandbox (runtime)
// ─────────────────────────────────────────────────────────────────────────

export interface SandboxOptions {
  /**
   * Maximum number of isolates (UDS connection slots) running concurrently.
   * The Sandbox maintains a pool of this many connections to the Rust process;
   * each executes one run() at a time. Additional callers queue.
   *
   * Multiple MCP agents / concurrent callers each get their own slot and
   * run in parallel up to this limit.
   *
   * Defaults to the number of logical CPUs on the host machine.
   */
  maxIsolates?: number

  /**
   * Override the path to the Rust V8 binary.
   * Default: auto-detect from \@iso4/v8-* platform packages.
   */
  binaryPath?: string
}

export interface Sandbox {
  /**
   * Execute a piece of JavaScript in a fresh V8 isolate.
   * For repeated use with a shared context, prefer precompile() + prefix.run().
   */
  run: (options: RunOptions) => Promise<RunResult>

  /**
   * Pre-compile a prefix of code into a V8 startup snapshot.
   *
   * The type parameter `G` is inferred from the `globals` you pass and flows
   * into the returned `Prefix<G>`. This lets TypeScript enforce at the call
   * site that `prefix.run()` can only rebind names declared here:
   *
   * ```ts
   * const prefix = await sandbox.precompile({
   *   globals: { fetch: myHandler, myTool: otherHandler },
   * })
   * // prefix: Prefix<{ fetch: ..., myTool: ... }>
   *
   * prefix.run({ globals: { fetch: newHandler } })          // ✅
   * prefix.run({ globals: { undeclared: someHandler } })    // ❌ TS error
   * ```
   *
   * Globals declared here serve as **default** implementations for all runs.
   * `prefix.run()` may override any subset; omitted names reuse the default.
   */

  /**
   * eslint-disable \@typescript-eslint/no-empty-object-type
   */
  precompile: <
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    G extends HostGlobals = {},
    // eslint-disable-next-line @typescript-eslint/no-empty-object-type
    M extends Imports = {},
  >(
    options: PrecompileOptions<G, M>,
  ) => Promise<Prefix<G, M>>

  /**
   * Tear down the Rust process. Outstanding prefixes are invalidated.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using sandbox = await createSandbox()` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

export type CreateSandbox = (options?: SandboxOptions) => Promise<Sandbox>

// ─────────────────────────────────────────────────────────────────────────
// Precompiled prefix
// ─────────────────────────────────────────────────────────────────────────

/**
 * Options for `sandbox.precompile()`.
 *
 * `G` is the shape of globals this prefix declares. TypeScript infers it
 * from the `globals` field, so the returned `Prefix<G>` is typed to allow
 * only those names to be rebound in subsequent `prefix.run()` calls.
 */
export interface PrecompileOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * ESM source code to evaluate before snapshotting. Top-level await works.
   *
   * @example
   *   import { search } from 'tools:search';
   *   globalThis.search = search;
   */
  code: string

  /**
   * Declares the globals that sandbox code will be able to call.
   *
   * This defines the **bridge surface shape** — the full set of names the
   * sandbox may invoke as globals. Names declared here:
   *
   * - Become bridge stubs in the V8 context on every `prefix.run()` call.
   * - Can be rebound per-run via `prefix.run({ globals })`.
   * - Cannot be supplemented at run time — a name not declared here will
   *   cause `ERR_UNDECLARED_BINDING` if passed to `prefix.run()`.
   *
   * The handlers provided here are the **default** implementations reused by
   * any `prefix.run()` call that does not override them.
   */
  globals?: G

  /**
   * Declares the imports the sandbox code may resolve.
   *
   * The inferred shape feeds `Prefix<G, M>` so `prefix.run()` knows which
   * specifiers exist and which exports may be rebound.
   */
  imports?: M

  /**
   * Resource limits applied to prefix code evaluation.
   *
   * **Important:** limits are NOT enforced during `precompile()`. Prefix code
   * is assumed to be developer-authored, not AI-agent-generated.
   *
   * **Currently a no-op placeholder.** Pass limits directly to each
   * `prefix.run()` call.
   */
  limits?: Partial<ResourceLimits>

  /**
   * Optional filename for stack traces. Default: "<prefix>".
   */
  filename?: string
}

/**
 * Handle to a precompiled prefix.
 *
 * `G` is the shape of globals declared at precompile time. `prefix.run()`
 * accepts only `Partial<G>` for its `globals` field — you may override any
 * declared global's implementation per run, but you cannot add names that
 * were not declared at precompile time.
 */
export interface Prefix<
  G extends HostGlobals,
  M extends Imports,
> {
  readonly id: string

  /**
   * Execute dynamic code against this prefix's snapshot state.
   *
   * Globals declared at precompile time are active. You may rebind any subset
   * of them via `options.globals`; the precompile-time handler is used for
   * any name not overridden here. Same rule for `imports`, restricted to
   * host-import function exports declared in `I`.
   *
   * @example
   *   const result = await prefix.run({
   *     code: `export default await (${agentFn})()`,
   *   })
   */
  run: (options: PrefixRunOptions<G, M>) => Promise<RunResult>

  /**
   * Release the snapshot. Subsequent run() calls reject. Idempotent.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using prefix = await sandbox.precompile(...)` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

/**
 * Options for `prefix.run()`.
 *
 * `G` is the declared-globals shape from the matching `precompile()` call.
 * The `globals` field is typed as `Partial<G>` — only names present in `G`
 * may be overridden. Passing any other name is a TypeScript error at compile
 * time and `ERR_UNDECLARED_BINDING` at runtime.
 */
export interface PrefixRunOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * Dynamic ESM source code to compile and run against the prefix state.
   */
  code: string

  /**
   * Override implementations for a **subset** of globals declared at
   * precompile time. Only names present in `G` are accepted (TypeScript
   * error + runtime `ERR_UNDECLARED_BINDING` for anything else), but the
   * function signature does not need to match the precompile-time handler
   * exactly — any `HostExportFunction`-compatible value is accepted.
   */
  globals?: RebindGlobals<G>

  /**
   * Rebind host-module function exports declared at precompile time.
   * Source module imports are frozen in the snapshot and cannot be rebound;
   * data exports are baked into the synthetic module. TypeScript enforces
   * this at the type level via `RebindImports<M>`; the runtime rejects
   * anything that slips through with `ERR_UNDECLARED_BINDING`.
   */
  imports?: RebindImports<M>

  limits?: Partial<ResourceLimits>
  signal?: AbortSignal
  filename?: string
}

// ─────────────────────────────────────────────────────────────────────────
// Direct run (no prefix)
// ─────────────────────────────────────────────────────────────────────────

export interface RunOptions {
  code: string
  limits?: Partial<ResourceLimits>
  globals?: HostGlobals
  imports?: Imports
  signal?: AbortSignal
  filename?: string
}

// ─────────────────────────────────────────────────────────────────────────
// Result
// ─────────────────────────────────────────────────────────────────────────

export type RunResult = RunSuccess | RunFailure

export interface RunSuccess {
  ok: true
  exports: SandboxExports
  stdout: string[]
  stderr: string[]
  durationMs: number
}

export interface RunFailure {
  ok: false
  error: RunError
  stdout: string[]
  stderr: string[]
  durationMs: number
}

export type SandboxExports = {
  /**
   * Value of `export default` in user code, or `undefined`.
   */
  default: unknown
} & {
  /**
   * Named exports live directly on the export object.
   */
  [name: string]: unknown
}

export interface RunError {
  code: RunErrorCode
  name: string
  message: string
  stack?: string
}

export type RunErrorCode
  = | 'ERR_USER_CODE'
    | 'ERR_MEMORY_LIMIT'
    | 'ERR_CPU_TIMEOUT'
    | 'ERR_WALL_TIMEOUT'
    | 'ERR_ABORTED'
    | 'ERR_MODULE_NOT_FOUND'
    | 'ERR_COMPILE'
    | 'ERR_FUNCTION_ARGUMENT_NOT_SUPPORTED'
    | 'ERR_EXPORT_NOT_SERIALIZABLE'
    | 'ERR_EXPORT_TOO_LARGE'
    | 'ERR_EXPORT_UNRESOLVED_PROMISE'
    | 'ERR_HOST_BRIDGE'
    | 'ERR_BRIDGE_PAYLOAD_TOO_LARGE'
    | 'ERR_BRIDGE_CALL_LIMIT_EXCEEDED'
    | 'ERR_UNDECLARED_BINDING'
    | 'ERR_PREFIX_DISPOSED'
    | 'ERR_INTERNAL'
