/* eslint-disable @typescript-eslint/no-empty-object-type */
/**
 * \@iso4/sandbox — public API types.
 *
 * Execution model: precompile a prefix once into a V8 startup snapshot,
 * then call prefix.run({ code }) for each piece of dynamic code (e.g.
 * agent-generated). A fresh isolate is created from the snapshot per call.
 * Multiple concurrent callers each get their own pool slot and run in
 * parallel. See DESIGN.md §1 and §13.
 */

// ─────────────────────────────────────────────────────────────────────────
// Resource limits
// ─────────────────────────────────────────────────────────────────────────

/**
 * Per-run resource caps. Every field is optional at the call site
 * (`limits?: ResourceLimits`): pass only the limits you want to
 * override. The client sends just those over the wire and the **runtime owns
 * the defaults** — it fills in any field you leave unset. The `@default` values
 * documented below mirror the runtime's defaults (defined in
 * `native/v8-runtime/src/ipc.rs`, the source of truth); if they ever drift, the
 * runtime wins.
 *
 * A field set to `0` is not the same as leaving it unset: `0` explicitly
 * disables that limit, whereas unset yields the runtime default.
 */
export interface ResourceLimits {
  /**
   * Hard cap on memory the isolate can use, in megabytes.
   * Covers the V8 heap and all external `ArrayBuffer` allocations.
   *
   * Also determines the BridgeResponse frame read cap: the sandbox cannot
   * receive a response larger than its own memory budget.
   *
   * Zero means no cap.
   * @default 64
   */
  memoryMb?: number

  /**
   * Maximum *active* execution time in milliseconds. Time spent waiting on
   * host bridge calls (globals, host imports) is excluded.
   * @default 5_000
   */
  cpuTimeMs?: number

  /**
   * Hard wall-clock cap including async waits.
   * @default 30_000
   */
  wallTimeMs?: number

  /**
   * Maximum bytes the sandbox may send as arguments in a single bridge call
   * (sandbox → host direction). Protects the host from receiving unexpectedly
   * large payloads generated by untrusted sandbox code.
   *
   * A violation terminates the run immediately with
   * `ERR_BRIDGE_PAYLOAD_TOO_LARGE`; sandbox code cannot catch it.
   *
   * Bridge responses (host → sandbox) are not separately capped here — the
   * natural limit is `memoryMb`: the sandbox cannot hold a response larger than
   * its own memory budget, and the framing layer enforces this automatically.
   *
   * Zero disables the per-call cap.
   * @default 16 * 1024 * 1024
   */
  maxBridgeCallBytes?: number

  /**
   * Maximum bytes allowed for the serialised export payload — one V8
   * serialization blob holding all exports combined. Exceeding this limit
   * terminates the run with `ERR_EXPORT_TOO_LARGE`.
   * Zero disables the cap.
   * @default 16 * 1024 * 1024
   */
  maxExportBytes?: number

  /**
   * Maximum bytes captured from `console.log` / `console.debug` / `console.info`
   * combined. Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStdoutBytes?: number

  /**
   * Maximum bytes captured from `console.warn` / `console.error` combined.
   * Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStderrBytes?: number

  /**
   * Maximum number of bridge calls (globals + host imports combined) a
   * single run may make. Zero disables the per-run limit entirely.
   *
   * Protects against untrusted sandbox code making unbounded calls to host
   * handlers (e.g. `while(true) { await myTool() }`) which consumes near-zero
   * CPU budget but can exhaust host resources (network, DB, LLM quota).
   *
   * A violation terminates the run immediately with
   * `ERR_BRIDGE_CALL_LIMIT_EXCEEDED`; sandbox code cannot catch it (unlike
   * host handler errors, which reject the call's promise and are catchable).
   *
   * @default 10
   */
  maxBridgeCalls?: number
}

// ─────────────────────────────────────────────────────────────────────────
// Globals (generic bridge — any non-reserved name is permitted)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Host-provided globals. Any name not reserved by V8 or the runtime is
 * permitted. Each value becomes a bridge stub in the sandbox global object.
 *
 * Reserved names (must not be used): `console`, `URL`, `URLSearchParams`,
 * `TextEncoder`, `TextDecoder`, `crypto`, `Event`, `AbortController`,
 * `AbortSignal`.
 *
 * Common usage:
 * ```ts
 * globals: {
 * fetch: myFetchHandler,   // \@iso4/fetch provides createSafeFetch()
 * myTool: async (arg) => doSomething(arg),
 * }
 * ```
 *
 * `fetch` is not special — it goes through the same bridge path as any
 * other entry.
 *
 * Three value shapes are supported — see `HostGlobalValue`.
 */
export type HostGlobals = Record<string, HostGlobalValue>

/**
 * The value types accepted for a named global.
 *
 * - `HostExportFunction` — bridge call: every sandbox invocation dispatches
 *   to the host handler.
 * - `string` — a JS expression the runtime evaluates once and installs as
 *   `globalThis.<name>`. Use for pure sandbox utilities that need no host
 *   involvement. The expression is evaluated by Rust as its own script, so it
 *   never shifts the line numbers of user code.
 * - `DataGlobal` — a plain constant carried as data and installed natively;
 *   no code text, no host involvement.
 * - `BridgeWithShim` — bridge call + in-sandbox result wrapper. The handler
 *   can be rebound per `prefix.run()`; the shim is compiled into the snapshot.
 */

export type HostGlobalValue = HostExportFunction | string | BridgeWithShim<any> | DataGlobal

/**
 * A plain **constant** global — a data value installed directly on the sandbox
 * global object, with no host involvement and no code text anywhere.
 *
 * The value crosses the wire as a V8 serialization blob and Rust materialises
 * it natively with `blob::deserialize_value` (the same path host-module data
 * leaves take):
 *
 * ```ts
 * globals: { config: { kind: 'data', value: userConfig } }
 * ```
 *
 * `value` accepts the same set as host-module data leaves (`HostExportData`):
 * primitives, `bigint`, `string`, `Uint8Array`, and plain objects/arrays.
 * Like string globals, a data global is a constant — it cannot be rebound per
 * `prefix.run()`.
 */
export interface DataGlobal {
  kind: 'data'
  value: HostExportData
}

/**
 * A global that pairs a bridge handler with an in-sandbox shim that wraps
 * its return value. Typical use: adding `.json()` / `.text()` convenience
 * methods to a fetch response without extra bridge round-trips.
 *
 * The runtime installs this natively:
 *  1. `handler` is registered as a bridge stub under the private dispatch
 *     name `__iso4_<name>_h`.
 *  2. Rust evaluates the shim expression and builds the wrapper
 *     `async (...args) => await shim(await globalThis["__iso4_<name>_h"](...args))`,
 *     then sets it on the global object under `<name>` via the V8 API — the
 *     public name is a plain string passed to `object.set`, never code.
 *
 * The shim is a JS function expression `(result) => transformedResult` (sync
 * or async). Sandbox built-ins (TextDecoder, JSON, …) are available in scope.
 * The private stub `__iso4_<name>_h` stays on globalThis so the handler can
 * be rebound per `prefix.run()` while the shim stays fixed in the snapshot.
 */
/**
 * `H` is the specific handler function type. Carried through the type system
 * so `RebindGlobals` can enforce that any per-run replacement has the same
 * return type, keeping it compatible with the shim that is already compiled
 * into the prefix snapshot.
 */
export interface BridgeWithShim<
  H extends (...args: unknown[]) => unknown = (...args: unknown[]) => unknown,
> {
  kind: 'bridge-with-shim'
  /**
   * Bridge handler — registered as `__iso4_<name>_h` for rebinding.
   */
  handler: H
  /**
   * JS function expression that transforms the bridge return value.
   * Runs in the sandbox. May be async.
   *
   * @example
   * ```ts
   * shim: `(result) => ({
   *   ...result,
   *   ok:   result.status >= 200 && result.status < 300,
   *   json: () => JSON.parse(new TextDecoder().decode(result.body)),
   *   text: () => new TextDecoder().decode(result.body),
   * })`
   * ```
   */
  shim: string
}

/**
 * What can be supplied as a per-run override for a global declared at
 * precompile time:
 *
 * - `BridgeWithShim<H>` global — only the handler `H` itself. The shim is
 *   fixed in the snapshot; rebinding must preserve the return type so the
 *   shim keeps working.
 * - `HostExportFunction` global — any compatible `HostExportFunction`.
 * - `string` global — cannot be rebound (compiled into the snapshot).
 */
export type RebindValue<V extends HostGlobalValue>
  = V extends BridgeWithShim<infer H> ? H
    : V extends HostExportFunction ? V
      : never

/**
 * The per-run globals override map for a `Prefix<G>`.
 *
 * String-valued and `DataGlobal` (constant) globals are filtered out entirely
 * (key remapping to `never`) rather than mapped to `?: never` — they cannot be
 * rebound because their value is compiled into the snapshot, and they should
 * not appear as valid keys at all.
 *
 * Each remaining key is optional and typed as `RebindValue<G[K]>`, which
 * enforces the correct constraint per global kind.
 */
export type RebindGlobals<G extends HostGlobals> = {
  [K in keyof G as G[K] extends string | DataGlobal ? never : K]?: RebindValue<G[K]>
}

// ─────────────────────────────────────────────────────────────────────────
// Imports
// ─────────────────────────────────────────────────────────────────────────
//
// `imports` is a flat map keyed by specifier. The value type discriminates:
//
//   string → source module: host provides ESM source. V8 compiles it inside
//     the isolate; transitive `import`s resolve back through the same map.
//     Zero per-call bridge cost.
//
//   object → host module: host provides a JS object describing the module
//     shape. The runtime walks the object recursively and generates ESM
//     source that exposes the structure: function leaves become async
//     stubs that issue bridge calls to a host-side handler, data leaves
//     become JS literals. Nested objects mixing data and functions are
//     supported natively.

/**
 * Top-level `imports` shape. Keys are import specifiers; values are either
 * a source string or a host-module description object.
 *
 * `M` is the literal shape of the map. `precompile()` infers it from the
 * object literal so the declared specifiers and their value shapes flow
 * into `Prefix<G, M>` and feed `RebindImports<M>`.
 */
export type Imports<M extends Record<string, ImportValue> = Record<string, ImportValue>> = M

/**
 * A single import value. String = source module. Object = host module
 * description (the recursive walker handles all nesting).
 */
export type ImportValue = string | HostModuleObject

/**
 * A host-module description object. Each property is either:
 *
 *   - A function — the runtime builds an async bridge trampoline for it.
 *   - A data value (anything in {@link HostExportData}) — materialised in the
 *     isolate from its V8 serialization blob.
 *   - A nested object that itself contains a mix of functions and data —
 *     walked recursively.
 *
 * Class instances with prototype methods and stateful handles (streams,
 * sockets) are rejected at registration with a clear error naming the exact
 * path: V8's format would carry them, but only as their own enumerable
 * properties, so the methods you meant to send would vanish silently. Copy
 * what you mean to send into a plain object.
 */
export interface HostModuleObject {
  [name: string]: HostModuleValue
}

/**
 * Any node the recursive walker may encounter inside a `HostModuleObject`.
 */
export type HostModuleValue
  = | HostExportFunction
    | HostExportData
    | HostModuleObject

/**
 * The set of data values that can cross the sandbox boundary.
 *
 * This mirrors what V8's serialization format can represent, so every value
 * here arrives on the other side as a **real instance** — a `Date` is a `Date`,
 * a `Map` is a `Map`, a `Float64Array` keeps its element type. Cyclic and
 * shared references are preserved, including object identity.
 *
 * What is *not* here cannot cross and is rejected loudly: functions (except as
 * declared function leaves), `Promise`, `Symbol`, `WeakMap`, `WeakSet`, and
 * `Proxy`. Class instances are also excluded — V8 would carry one, but only as
 * its own enumerable properties, silently dropping its prototype and methods.
 *
 * Two notes for hosts:
 *
 * - Node `Buffer` is a `Uint8Array` subclass, so it crosses fine, but it
 *   arrives as a plain `Uint8Array` (data preserved, subclass identity not).
 * - A `subarray` window carries only the bytes in its window.
 *
 * @see `docs/protocol.md` §4.2 for the full table, both directions.
 */
export type HostExportData
  = | null
    | undefined
    | boolean
    | number
    | bigint
    | string
    | Date
    | RegExp
    | Error
    | Map<HostExportData, HostExportData>
    | Set<HostExportData>
    | ArrayBuffer
    | DataView
    | Int8Array
    | Uint8Array
    | Uint8ClampedArray
    | Int16Array
    | Uint16Array
    | Int32Array
    | Uint32Array
    | Float32Array
    | Float64Array
    | BigInt64Array
    | BigUint64Array
    | HostExportData[]
    | { [key: string]: HostExportData }

/**
 * A host-side function exposed as a global or import-tree leaf.
 *
 * Args and return are `unknown` — the bridge serialises/deserialises values
 * with V8 ValueSerializer; we don't try to model that at the type level.
 * The one invariant that matters (functions cannot cross the boundary as
 * argument values) is enforced at runtime by the V8 layer, not here.
 *
 * Use specific function types for your handlers and let TypeScript infer
 * them through `HostGlobals`, `RebindGlobals<G>`, and `RebindImports<M>`.
 */
export type HostExportFunction = (...args: unknown[]) => unknown

/**
 * The rebindable subset of an `Imports<M>` declared at precompile time.
 *
 * Mirrors `RebindGlobals<G>` over the recursive host-module shape:
 *
 * - **Source imports** (string values) are compiled into the snapshot and
 *   cannot be rebound — their keys are excluded from the result.
 * - **Host imports** (object values) are walked recursively. Only function
 *   leaves survive; data leaves are excluded because their values are
 *   emitted as JS literals into the generated module.
 *
 * Passing a specifier or export name that was not declared at precompile
 * is a TypeScript error at compile time and `ERR_UNDECLARED_BINDING` at
 * runtime.
 *
 * When `M` is left at its wide default (no `imports` declared, or no
 * literal shape inferred), the rebind keyspace collapses to
 * `Record<string, never>` — the walker only kicks in for literal shapes,
 * which have finite depth.
 */
export type RebindImports<M extends Record<string, ImportValue>>
  = Record<string, ImportValue> extends M
    ? Record<string, never>
    : {
        [K in keyof M as M[K] extends string ? never : K]?:
        M[K] extends HostModuleObject ? RebindHostModule<M[K]> : never
      }

/**
 * Recursive walker over a `HostModuleObject`. Function leaves keep
 * their declared signature; nested objects recurse; data leaves drop out
 * entirely. Only used against literal shapes inferred by `precompile`, so
 * the recursion is always finite.
 */
export type RebindHostModule<T> = T extends HostExportFunction
  ? T
  : T extends HostModuleObject
    ? {
        [K in keyof T as T[K] extends HostExportFunction
          ? K
          : T[K] extends HostModuleObject
            ? K
            : never]?: T[K] extends HostExportFunction
          ? T[K]
          : T[K] extends HostModuleObject
            ? RebindHostModule<T[K]>
            : never
      }
    : never

// ─────────────────────────────────────────────────────────────────────────
// Sandbox (runtime)
// ─────────────────────────────────────────────────────────────────────────

export interface SandboxOptions {
  /**
   * Maximum number of isolates (UDS connection slots) running concurrently.
   * The Sandbox maintains a pool of this many connections to the Rust process;
   * each executes one run() at a time. Additional callers queue.
   *
   * Multiple MCP agents / concurrent callers each get their own slot and
   * run in parallel up to this limit.
   *
   * Defaults to the number of logical CPUs on the host machine.
   */
  maxIsolates?: number

  /**
   * Override the path to the Rust V8 binary.
   * Default: auto-detect from \@iso4/v8-* platform packages.
   */
  binaryPath?: string
}

export interface Sandbox {
  /**
   * Execute a piece of JavaScript in a fresh V8 isolate.
   * For repeated use with a shared context, prefer precompile() + prefix.run().
   */
  run: (options: RunOptions) => Promise<RunResult>

  /**
   * Pre-compile a prefix of code into a V8 startup snapshot.
   *
   * The type parameter `G` is inferred from the `globals` you pass and flows
   * into the returned `Prefix<G>`. This lets TypeScript enforce at the call
   * site that `prefix.run()` can only rebind names declared here:
   *
   * ```ts
   * const prefix = await sandbox.precompile({
   *   globals: { fetch: myHandler, myTool: otherHandler },
   * })
   * // prefix: Prefix<{ fetch: ..., myTool: ... }>
   *
   * prefix.run({ globals: { fetch: newHandler } })          // ✅
   * prefix.run({ globals: { undeclared: someHandler } })    // ❌ TS error
   * ```
   *
   * Globals declared here serve as **default** implementations for all runs.
   * `prefix.run()` may override any subset; omitted names reuse the default.
   */

  /**
   * eslint-disable \@typescript-eslint/no-empty-object-type
   */
  prepare: <
    G extends HostGlobals = {},
    M extends Imports = {},
  >(
    options: PrecompileOptions<G, M>,
  ) => Promise<Prefix<G, M>>

  /**
   * @deprecated Renamed to {@link Sandbox.prepare}. `precompile` stays as an
   * alias (identical behavior) and is slated for removal in a future major.
   */
  precompile: <
    G extends HostGlobals = {},
    M extends Imports = {},
  >(
    options: PrecompileOptions<G, M>,
  ) => Promise<Prefix<G, M>>

  /**
   * Tear down the Rust process. Outstanding prefixes are invalidated.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using sandbox = await createSandbox()` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

export type CreateSandbox = (options?: SandboxOptions) => Promise<Sandbox>

// ─────────────────────────────────────────────────────────────────────────
// Precompiled prefix
// ─────────────────────────────────────────────────────────────────────────

/**
 * Options for `sandbox.precompile()`.
 *
 * `G` is the shape of globals this prefix declares. TypeScript infers it
 * from the `globals` field, so the returned `Prefix<G>` is typed to allow
 * only those names to be rebound in subsequent `prefix.run()` calls.
 */
export interface PrecompileOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * ESM source code to evaluate before snapshotting. Top-level await works.
   *
   * @example
   *   import { search } from 'tools:search';
   *   globalThis.search = search;
   */
  code: string

  /**
   * Declares the globals that sandbox code will be able to call.
   *
   * This defines the **bridge surface shape** — the full set of names the
   * sandbox may invoke as globals. Names declared here:
   *
   * - Become bridge stubs in the V8 context on every `prefix.run()` call.
   * - Can be rebound per-run via `prefix.run({ globals })`.
   * - Cannot be supplemented at run time — a name not declared here will
   *   cause `ERR_UNDECLARED_BINDING` if passed to `prefix.run()`.
   *
   * The handlers provided here are the **default** implementations reused by
   * any `prefix.run()` call that does not override them.
   */
  globals?: G

  /**
   * Declares the imports the sandbox code may resolve.
   *
   * The inferred shape feeds `Prefix<G, M>` so `prefix.run()` knows which
   * specifiers exist and which exports may be rebound.
   */
  imports?: M

  /**
   * Resource limits applied to prefix code evaluation.
   *
   * **Important:** limits are NOT enforced during `precompile()`. Prefix code
   * is assumed to be developer-authored, not AI-agent-generated.
   *
   * **Currently a no-op placeholder.** Pass limits directly to each
   * `prefix.run()` call.
   */
  limits?: ResourceLimits

  /**
   * Optional filename for stack traces. Default: "<prefix>".
   */
  filename?: string
}

/**
 * Handle to a precompiled prefix.
 *
 * `G` is the shape of globals declared at precompile time. `prefix.run()`
 * accepts only `Partial<G>` for its `globals` field — you may override any
 * declared global's implementation per run, but you cannot add names that
 * were not declared at precompile time.
 */
export interface Prefix<
  G extends HostGlobals = {},
  M extends Imports = {},
> {
  readonly id: string

  /**
   * Execute dynamic code against this prefix's snapshot state.
   *
   * Globals declared at precompile time are active. You may rebind any subset
   * of them via `options.globals`; the precompile-time handler is used for
   * any name not overridden here. Same rule for `imports`, restricted to
   * host-import function exports declared in `I`.
   *
   * @example
   *   const result = await prefix.execute({
   *     code: `export default await (${agentFn})()`,
   *   })
   */
  execute: (options: PrefixRunOptions<G, M>) => Promise<RunResult>

  /**
   * @deprecated Renamed to {@link Prefix.execute}. `run` stays as an alias
   * (identical behavior) and is slated for removal in a future major.
   */
  run: (options: PrefixRunOptions<G, M>) => Promise<RunResult>

  /**
   * Release the snapshot. Subsequent run() calls reject. Idempotent.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using prefix = await sandbox.precompile(...)` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

/**
 * Options for `prefix.run()`.
 *
 * `G` is the declared-globals shape from the matching `precompile()` call.
 * The `globals` field is typed as `Partial<G>` — only names present in `G`
 * may be overridden. Passing any other name is a TypeScript error at compile
 * time and `ERR_UNDECLARED_BINDING` at runtime.
 */
export interface PrefixRunOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * Dynamic ESM source code to compile and run against the prefix state.
   */
  code: string

  /**
   * Override implementations for a **subset** of globals declared at
   * precompile time. Only names present in `G` are accepted (TypeScript
   * error + runtime `ERR_UNDECLARED_BINDING` for anything else), but the
   * function signature does not need to match the precompile-time handler
   * exactly — any `HostExportFunction`-compatible value is accepted.
   */
  globals?: RebindGlobals<G>

  /**
   * Rebind host-module function exports declared at precompile time.
   * Source module imports are frozen in the snapshot and cannot be rebound;
   * data exports are baked into the synthetic module. TypeScript enforces
   * this at the type level via `RebindImports<M>`; the runtime rejects
   * anything that slips through with `ERR_UNDECLARED_BINDING`.
   */
  imports?: RebindImports<M>

  limits?: ResourceLimits
  signal?: AbortSignal
  filename?: string
}

// ─────────────────────────────────────────────────────────────────────────
// Direct run (no prefix)
// ─────────────────────────────────────────────────────────────────────────

export interface RunOptions {
  code: string
  limits?: ResourceLimits
  globals?: HostGlobals
  imports?: Imports
  signal?: AbortSignal
  filename?: string
}

// ─────────────────────────────────────────────────────────────────────────
// Result
// ─────────────────────────────────────────────────────────────────────────

/**
 * Why a run was aborted — whatever value was passed to the aborting
 * `AbortController.abort(reason)` (or left `undefined`). Opaque to iso4 and
 * surfaced verbatim on {@link RunAborted.reason}; a consumer built on top
 * (e.g. a durable-workflow kernel expressing "suspend") gives it meaning.
 */
export type AbortReason = unknown

export type RunResult = RunSuccess | RunFailure | RunAborted

/**
 * Metadata for a single bridge call attempt, recorded by the Rust runtime on
 * the run's own clock. No payloads — names, timing, and sizes only — so
 * recording is cheap enough to stay always-on. Unbounded: every attempt gets
 * an entry (~100 bytes); consumers that only care about a subset filter the
 * list themselves.
 */
export interface BridgeCallEntry {
  /**
   * The name sandbox code called. Plain globals appear as-is (`fetch`),
   * shimmed globals under their public name (not the private stub), and
   * host-module import leaves as `<specifier>.<path>` (e.g.
   * `tools:search.query`).
   */
  name: string
  /**
   * Offset from run start to the attempt, in milliseconds — same clock as
   * the result's `durationMs`, so entries line up on a run timeline.
   */
  startMs: number
  /**
   * Round-trip time the sandbox waited for the response (host handler + IPC),
   * in milliseconds. For calls still unanswered when the run ended
   * (timeout/abort): the time until the run ended. `0` for blocked attempts.
   */
  durationMs: number
  /**
   * Serialized size of the call payload (callId + target + arguments) in
   * bytes — the same size `maxBridgeCallBytes` is enforced against. `0` for
   * attempts blocked before argument serialization.
   */
  argBytes: number
  /**
   * Serialized size of the successful response value in bytes. `0` when the
   * handler failed or the call never settled.
   */
  responseBytes: number
  /**
   * `true` when the host handler resolved and its response reached the
   * sandbox. `false` for handler errors, blocked attempts, and calls still
   * in flight when the run ended.
   */
  ok: boolean
  /**
   * `true` when the attempt was blocked inside the runtime (`maxBridgeCalls`
   * exceeded, payload over `maxBridgeCallBytes`, function argument) and never
   * reached the host.
   */
  blocked: boolean
}

/**
 * `status` is the primary discriminant across all three outcomes; `ok` is kept
 * as a convenience alias for `status === 'completed'`, so the common guard
 * stays `if (result.ok)`. Reach for `switch (result.status)` when a deliberate
 * abort must be told apart from a genuine failure.
 */
export interface RunSuccess {
  status: 'completed'
  ok: true
  exports: SandboxExports
  stdout: string[]
  stderr: string[]
  /**
   * Wall-clock time of the run (start of execution to result), measured in
   * the runtime. Milliseconds with microsecond resolution.
   */
  durationMs: number
  /**
   * Active V8 execution time — time spent waiting on host bridge calls is
   * excluded. Milliseconds with microsecond resolution. The remainder
   * (`durationMs - cpuTimeMs`) is bridge waits plus scheduling.
   */
  cpuTimeMs: number
  /**
   * One entry per bridge call the sandbox attempted, in attempt order —
   * including attempts blocked by limits ({@link BridgeCallEntry.blocked}).
   * Recorded by the Rust runtime.
   */
  bridgeCalls: BridgeCallEntry[]
}

export interface RunFailure {
  status: 'failed'
  ok: false
  error: RunError
  stdout: string[]
  stderr: string[]
  durationMs: number
  cpuTimeMs: number
  bridgeCalls: BridgeCallEntry[]
}

/**
 * The run was stopped by an abort — a pre-aborted or mid-run `signal` passed to
 * `run()`, or a host handler that aborted the run. A deliberate outcome, not a
 * crash: `error` is retained (its `code` is always `ERR_ABORTED`) so existing
 * `!result.ok` / `error.code` checks keep working, and `reason` carries the
 * value handed to `abort(reason)`.
 */
export interface RunAborted {
  status: 'aborted'
  ok: false
  error: RunError
  reason?: AbortReason
  stdout: string[]
  stderr: string[]
  durationMs: number
  cpuTimeMs: number
  /**
   * Bridge calls recorded before the abort landed. Populated when the runtime
   * terminates gracefully (#36) — the common case, where the run was suspended
   * awaiting a bridge response. Empty (and `durationMs`/`cpuTimeMs` zero) only
   * when graceful termination falls back to socket teardown — e.g. a run
   * aborted while stuck in a tight synchronous loop, or a signal already
   * aborted at run entry.
   */
  bridgeCalls: BridgeCallEntry[]
}

export type SandboxExports = {
  /**
   * Value of `export default` in user code, or `undefined`.
   */
  default: unknown
} & {
  /**
   * Named exports live directly on the export object.
   */
  [name: string]: unknown
}

export interface RunError {
  code: RunErrorCode
  name: string
  message: string
  /**
   * Stack trace of the thrown error. `name`/`message`/`stack` are reserved:
   * they are always read from the error's dedicated properties and never
   * appear inside `fields`, so a thrown object cannot spoof them there.
   */
  stack?: string
  /**
   * All other own enumerable properties of the thrown error (everything
   * except name/message/stack), e.g. `status`, `reason`, or a `data` payload
   * from a custom error class — nested here so nothing can collide with
   * `code`. Present for ERR_USER_CODE and ERR_HOST_BRIDGE when the thrown
   * value is an object with serializable own properties.
   */
  fields?: Record<string, unknown>
}

export type RunErrorCode
  = | 'ERR_USER_CODE'
    | 'ERR_MEMORY_LIMIT'
    | 'ERR_CPU_TIMEOUT'
    | 'ERR_WALL_TIMEOUT'
    | 'ERR_ABORTED'
    | 'ERR_MODULE_NOT_FOUND'
    | 'ERR_COMPILE'
    | 'ERR_FUNCTION_ARGUMENT_NOT_SUPPORTED'
    | 'ERR_EXPORT_NOT_SERIALIZABLE'
    /**
     * A registered host type (`Request`, `Response`, …) cannot cross this
     * boundary in this position — an unimplemented tag, or content that is not
     * self-contained such as a stream body. See `docs/protocol.md` §4.4.5.
     */
    | 'ERR_TYPE_NOT_SERIALIZABLE'
    | 'ERR_EXPORT_TOO_LARGE'
    | 'ERR_EXPORT_UNRESOLVED_PROMISE'
    | 'ERR_HOST_BRIDGE'
    | 'ERR_BRIDGE_PAYLOAD_TOO_LARGE'
    | 'ERR_BRIDGE_CALL_LIMIT_EXCEEDED'
    | 'ERR_UNDECLARED_BINDING'
    | 'ERR_PREFIX_DISPOSED'
    | 'ERR_INTERNAL'
