/* eslint-disable @typescript-eslint/no-empty-object-type */
/**
 * \@iso4/sandbox — public API types.
 *
 * Execution model: prepare a prefix once (validated and cached by the
 * runtime), then run many dynamic postfixes against it (typically
 * agent-generated) with `prefix.execute({ code })` or invoke one of its
 * exports with `prefix.call({ export, args })`. Prefix runs are served by
 * resident warm instances, which skip isolate boot and prefix evaluation on
 * reuse; a one-off `sandbox.run({ code })` always gets a fresh isolate.
 * Multiple concurrent callers each get their own pool slot and run in
 * parallel. See DESIGN.md §1 and §13.
 */

// ─────────────────────────────────────────────────────────────────────────
// Resource limits
// ─────────────────────────────────────────────────────────────────────────

/**
 * Per-run resource caps. Every field is optional at the call site
 * (`limits?: ResourceLimits`): pass only the limits you want to
 * override. The client sends just those over the wire and the **runtime owns
 * the defaults** — it fills in any field you leave unset. The `@default` values
 * documented below mirror the runtime's defaults (defined in
 * `native/v8-runtime/src/ipc.rs`, the source of truth); if they ever drift, the
 * runtime wins.
 *
 * A field set to `0` is not the same as leaving it unset: `0` explicitly
 * disables that limit, whereas unset yields the runtime default.
 */
export interface ResourceLimits {
  /**
   * Maximum *active* execution time in milliseconds. Time spent waiting on
   * host bridge calls (globals, host imports) is excluded.
   * @default 5_000
   */
  cpuTimeMs?: number

  /**
   * Hard wall-clock cap including async waits.
   * @default 30_000
   */
  wallTimeMs?: number

  /**
   * Maximum bytes the sandbox may send as arguments in a single bridge call
   * (sandbox → host direction). Protects the host from receiving unexpectedly
   * large payloads generated by untrusted sandbox code.
   *
   * A violation terminates the run immediately with
   * `ERR_BRIDGE_PAYLOAD_TOO_LARGE`; sandbox code cannot catch it.
   *
   * Bridge responses (host → sandbox) are not separately capped here. The
   * binding limit is the host framing ceiling of 64 MiB, below the runtime's own
   * inbound allowance of `memoryMb`: a handler returning more than that cannot
   * be encoded, and the sandbox receives `ERR_HOST_BRIDGE` for that call rather
   * than the value. Cap large handler return values yourself if you want a
   * cleaner failure.
   *
   * Zero disables the per-call cap.
   * @default 16 * 1024 * 1024
   */
  maxBridgeCallBytes?: number

  /**
   * Maximum bytes allowed for the serialised export payload — one V8
   * serialization blob holding all exports combined. Exceeding this limit
   * terminates the run with `ERR_EXPORT_TOO_LARGE`.
   * Zero disables the cap.
   * @default 16 * 1024 * 1024
   */
  maxExportBytes?: number

  /**
   * Maximum bytes captured from `console.log` / `console.debug` / `console.info`
   * combined. Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStdoutBytes?: number

  /**
   * Maximum bytes captured from `console.warn` / `console.error` combined.
   * Lines that would push the total over the limit are silently dropped.
   * Zero disables the cap.
   * @default 1 * 1024 * 1024
   */
  maxStderrBytes?: number

  /**
   * Maximum number of bridge calls (globals + host imports combined) a
   * single run may make. Zero disables the per-run limit entirely.
   *
   * Protects against untrusted sandbox code making unbounded calls to host
   * handlers (e.g. `while(true) { await myTool() }`) which consumes near-zero
   * CPU budget but can exhaust host resources (network, DB, LLM quota).
   *
   * A violation terminates the run immediately with
   * `ERR_BRIDGE_CALL_LIMIT_EXCEEDED`; sandbox code cannot catch it (unlike
   * host handler errors, which reject the call's promise and are catchable).
   *
   * @default 10
   */
  maxBridgeCalls?: number

  /**
   * Wall budget in milliseconds for `waitUntil` background work after the
   * run's value has been delivered. One budget for the whole registered
   * set, started when the result ships. Grace work additionally gets a fresh
   * CPU allotment sized like `cpuTimeMs`. `0` disables the grace phase
   * entirely: registered work dies when the value settles.
   * @default 30_000
   */
  graceMs?: number
}

// ─────────────────────────────────────────────────────────────────────────
// Globals (generic bridge — any non-reserved name is permitted)
// ─────────────────────────────────────────────────────────────────────────

/**
 * Host-provided globals. Any name not reserved by V8 or the runtime is
 * permitted. Each value becomes a bridge stub in the sandbox global object.
 *
 * Reserved names (rejected with `ERR_UNDECLARED_BINDING`): `console`,
 * `waitUntil`, `setTimeout`, `clearTimeout`, `Headers`, `Request`,
 * `Response`, `TextEncoder`, `TextDecoder`, `URL`, `URLSearchParams`. These
 * are owned by the runtime; shadowing `Response` would silently break
 * serialization.
 *
 * Common usage:
 * ```ts
 * globals: {
 * fetch: myFetchHandler,   // \@iso4/fetch provides createSafeFetch()
 * myTool: async (arg) => doSomething(arg),
 * }
 * ```
 *
 * `fetch` is not special — it goes through the same bridge path as any
 * other entry.
 *
 * Three value shapes are supported — see `HostGlobalValue`.
 */
export type HostGlobals = Record<string, HostGlobalValue>

/**
 * The value types accepted for a named global.
 *
 * - `HostExportFunction` — bridge call: every sandbox invocation dispatches
 *   to the host handler. Shorthand for `BridgeGlobal` with the defaults.
 * - `string` — a JS expression the runtime evaluates once and installs as
 *   `globalThis.<name>`. Use for pure sandbox utilities that need no host
 *   involvement. The expression is evaluated by Rust as its own script, so it
 *   never shifts the line numbers of user code. Shorthand for `StringGlobal`
 *   with the defaults.
 * - `BridgeGlobal` / `StringGlobal` — the same two as object forms, for when
 *   an option (`enumerable`) is needed.
 * - `DataGlobal` — a plain constant carried as data and installed natively;
 *   no code text, no host involvement.
 * - `BridgeWithShim` — bridge call + in-sandbox result wrapper. The handler
 *   can be rebound per `prefix.run()`; the shim is part of the prefix state.
 *
 * Every **object** form accepts `enumerable?: boolean` (default `true`).
 * The bare-function and bare-string shorthands are always enumerable.
 */

export type HostGlobalValue
  = HostExportFunction | string | BridgeWithShim<any> | DataGlobal | BridgeGlobal<any> | StringGlobal

/**
 * Shared option of every object-form global.
 *
 * `enumerable: false` keeps the name out of `for...in`, `Object.keys`, and
 * spreads of `globalThis`, so enumeration-driven sandbox code (serializers,
 * "copy the environment" patterns) never sweeps it up. This is hygiene, not
 * secrecy: the property still appears in `Object.getOwnPropertyNames` (a
 * language-level fact, identical in every engine), and code that knows the
 * name can still call it. A capability that must be undiscoverable belongs in
 * `imports`, which nothing can enumerate.
 */
export interface GlobalOptions {
  /**
   * Whether the installed global shows up in enumeration. Defaults to `true`,
   * matching how browsers keep `fetch` enumerable on `window`.
   */
  enumerable?: boolean
}

/**
 * Object form of the bare-function bridge global, for when options are
 * needed. `handler` is exactly the function the shorthand would be.
 *
 * ```ts
 * globals: { myTool: { kind: 'bridge', handler: async (q) => search(q), enumerable: false } }
 * ```
 */
export interface BridgeGlobal<
  H extends HostExportFunction = HostExportFunction,
> extends GlobalOptions {
  kind: 'bridge'
  /**
   * Bridge handler — every sandbox invocation dispatches to it. Can be
   * rebound per `prefix.run()` like a shorthand bridge global.
   */
  handler: H
}

/**
 * Object form of the bare-string expression global, for when options are
 * needed. `expr` is exactly the expression the shorthand would be.
 */
export interface StringGlobal extends GlobalOptions {
  kind: 'string'
  /**
   * JS expression the runtime evaluates once and installs under the name.
   */
  expr: string
}

/**
 * A plain **constant** global — a data value installed directly on the sandbox
 * global object, with no host involvement and no code text anywhere.
 *
 * The value crosses the wire as a V8 serialization blob and Rust materialises
 * it natively with `blob::deserialize_value` (the same path host-module data
 * leaves take):
 *
 * ```ts
 * globals: { config: { kind: 'data', value: userConfig } }
 * ```
 *
 * `value` accepts the same set as host-module data leaves (`HostExportData`):
 * primitives, `bigint`, `string`, `Uint8Array`, and plain objects/arrays.
 * Like string globals, a data global is a constant — it cannot be rebound per
 * `prefix.run()`.
 */
export interface DataGlobal extends GlobalOptions {
  kind: 'data'
  /**
   * Any `HostExportData`, or a `Request`/`Response`/`Headers` — including nested
   * inside a plain object or array, which the runtime rebuilds as real instances
   * (`docs/protocol.md` §4.4).
   */
  value: HostExportData | Request | Response | Headers
}

/**
 * A global that pairs a bridge handler with an in-sandbox shim that wraps
 * its return value. Typical use: adding `.json()` / `.text()` convenience
 * methods to a fetch response without extra bridge round-trips.
 *
 * The runtime installs this natively:
 *  1. `handler` is registered as a bridge stub under the private dispatch
 *     name `__iso4_<name>_h`.
 *  2. Rust evaluates the shim expression and builds the wrapper
 *     `async (...args) => await shim(await globalThis["__iso4_<name>_h"](...args))`,
 *     then sets it on the global object under `<name>` via the V8 API — the
 *     public name is a plain string passed to `object.set`, never code.
 *
 * The shim is a JS function expression `(result) => transformedResult` (sync
 * or async). Sandbox built-ins (TextDecoder, JSON, …) are available in scope.
 * The private stub `__iso4_<name>_h` stays on globalThis so the handler can
 * be rebound per `prefix.run()` while the shim itself stays fixed.
 */
/**
 * `H` is the specific handler function type. Carried through the type system
 * so `RebindGlobals` can enforce that any per-run replacement has the same
 * return type, keeping it compatible with the shim that is already compiled
 * into the prefix state.
 */
export interface BridgeWithShim<
  H extends (...args: unknown[]) => unknown = (...args: unknown[]) => unknown,
> extends GlobalOptions {
  kind: 'bridge-with-shim'
  /**
   * Bridge handler — registered as `__iso4_<name>_h` for rebinding.
   */
  handler: H
  /**
   * JS function expression that transforms the bridge return value.
   * Runs in the sandbox. May be async.
   *
   * @example
   * ```ts
   * shim: `(result) => ({
   *   ...result,
   *   ok:   result.status >= 200 && result.status < 300,
   *   json: () => JSON.parse(new TextDecoder().decode(result.body)),
   *   text: () => new TextDecoder().decode(result.body),
   * })`
   * ```
   */
  shim: string
}

/**
 * What can be supplied as a per-run override for a global declared at
 * precompile time:
 *
 * - `BridgeWithShim<H>` global — only the handler `H` itself. The shim is
 *   fixed with the prefix; rebinding must preserve the return type so the
 *   shim keeps working.
 * - `HostExportFunction` global — any compatible `HostExportFunction`.
 * - `string` global — cannot be rebound (fixed at prepare() time).
 */
export type RebindValue<V extends HostGlobalValue>
  = V extends BridgeWithShim<infer H> ? H
    : V extends BridgeGlobal<infer H> ? H
      : V extends HostExportFunction ? V
        : never

/**
 * The per-run globals override map for a `Prefix<G>`.
 *
 * String-valued and `DataGlobal` (constant) globals are filtered out entirely
 * (key remapping to `never`) rather than mapped to `?: never` — they cannot be
 * rebound because their value is fixed at prepare() time, and they should
 * not appear as valid keys at all.
 *
 * Each remaining key is optional and typed as `RebindValue<G[K]>`, which
 * enforces the correct constraint per global kind.
 */
export type RebindGlobals<G extends HostGlobals> = {
  [K in keyof G as G[K] extends string | DataGlobal | StringGlobal ? never : K]?: RebindValue<G[K]>
}

// ─────────────────────────────────────────────────────────────────────────
// Imports
// ─────────────────────────────────────────────────────────────────────────
//
// `imports` is a flat map keyed by specifier. The value type discriminates:
//
//   string → source module: host provides ESM source. V8 compiles it inside
//     the isolate; transitive `import`s resolve back through the same map.
//     Zero per-call bridge cost.
//
//   object → host module: host provides a JS object describing the module
//     shape. The runtime walks the object recursively and generates ESM
//     source that exposes the structure: function leaves become async
//     stubs that issue bridge calls to a host-side handler, data leaves
//     become JS literals. Nested objects mixing data and functions are
//     supported natively.

/**
 * Top-level `imports` shape. Keys are import specifiers; values are either
 * a source string or a host-module description object.
 *
 * `M` is the literal shape of the map. `precompile()` infers it from the
 * object literal so the declared specifiers and their value shapes flow
 * into `Prefix<G, M>` and feed `RebindImports<M>`.
 */
export type Imports<M extends Record<string, ImportValue> = Record<string, ImportValue>> = M

/**
 * A single import value. String = source module. Object = host module
 * description (the recursive walker handles all nesting).
 */
export type ImportValue = string | HostModuleObject

/**
 * A host-module description object. Each property is either:
 *
 *   - A function — the runtime builds an async bridge trampoline for it.
 *   - A data value (anything in {@link HostExportData}) — materialised in the
 *     isolate from its V8 serialization blob.
 *   - A nested object that itself contains a mix of functions and data —
 *     walked recursively.
 *
 * Class instances with prototype methods and stateful handles (streams,
 * sockets) are rejected at registration with a clear error naming the exact
 * path: V8's format would carry them, but only as their own enumerable
 * properties, so the methods you meant to send would vanish silently. Copy
 * what you mean to send into a plain object.
 */
export interface HostModuleObject {
  [name: string]: HostModuleValue
}

/**
 * Any node the recursive walker may encounter inside a `HostModuleObject`.
 */
export type HostModuleValue
  = | HostExportFunction
    | HostExportData
    | HostModuleObject

/**
 * The set of data values that can cross the sandbox boundary.
 *
 * This mirrors what V8's serialization format can represent, so every value
 * here arrives on the other side as a **real instance** — a `Date` is a `Date`,
 * a `Map` is a `Map`, a `Float64Array` keeps its element type. Cyclic and
 * shared references are preserved, including object identity.
 *
 * What is *not* here cannot cross and is rejected loudly: functions (except as
 * declared function leaves), `Promise`, `Symbol`, `WeakMap`, `WeakSet`, and
 * `Proxy`. Class instances are also excluded — V8 would carry one, but only as
 * its own enumerable properties, silently dropping its prototype and methods.
 *
 * Two notes for hosts:
 *
 * - Node `Buffer` is a `Uint8Array` subclass, so it crosses fine, but it
 *   arrives as a plain `Uint8Array` (data preserved, subclass identity not).
 * - A `subarray` window carries only the bytes in its window.
 *
 * @see `docs/protocol.md` §4.2 for the full table, both directions.
 */
export type HostExportData
  = | null
    | undefined
    | boolean
    | number
    | bigint
    | string
    | Date
    | RegExp
    | Error
    | Map<HostExportData, HostExportData>
    | Set<HostExportData>
    | ArrayBuffer
    | DataView
    | Int8Array
    | Uint8Array
    | Uint8ClampedArray
    | Int16Array
    | Uint16Array
    | Int32Array
    | Uint32Array
    | Float32Array
    | Float64Array
    | BigInt64Array
    | BigUint64Array
    | HostExportData[]
    | { [key: string]: HostExportData }

/**
 * A host-side function exposed as a global or import-tree leaf.
 *
 * Args and return are `unknown` — the bridge serialises/deserialises values
 * with V8 ValueSerializer; we don't try to model that at the type level.
 * The one invariant that matters (functions cannot cross the boundary as
 * argument values) is enforced at runtime by the V8 layer, not here.
 *
 * Use specific function types for your handlers and let TypeScript infer
 * them through `HostGlobals`, `RebindGlobals<G>`, and `RebindImports<M>`.
 */
export type HostExportFunction = (...args: unknown[]) => unknown

/**
 * The rebindable subset of an `Imports<M>` declared at precompile time.
 *
 * Mirrors `RebindGlobals<G>` over the recursive host-module shape:
 *
 * - **Source imports** (string values) are fixed at prepare() time and
 *   cannot be rebound — their keys are excluded from the result.
 * - **Host imports** (object values) are walked recursively. Only function
 *   leaves survive; data leaves are excluded because their values are
 *   emitted as JS literals into the generated module.
 *
 * Passing a specifier or export name that was not declared at precompile
 * is a TypeScript error at compile time and `ERR_UNDECLARED_BINDING` at
 * runtime.
 *
 * When `M` is left at its wide default (no `imports` declared, or no
 * literal shape inferred), the rebind keyspace collapses to
 * `Record<string, never>` — the walker only kicks in for literal shapes,
 * which have finite depth.
 */
export type RebindImports<M extends Record<string, ImportValue>>
  = Record<string, ImportValue> extends M
    ? Record<string, never>
    : {
        [K in keyof M as M[K] extends string ? never : K]?:
        M[K] extends HostModuleObject ? RebindHostModule<M[K]> : never
      }

/**
 * Recursive walker over a `HostModuleObject`. Function leaves keep
 * their declared signature; nested objects recurse; data leaves drop out
 * entirely. Only used against literal shapes inferred by `precompile`, so
 * the recursion is always finite.
 */
export type RebindHostModule<T> = T extends HostExportFunction
  ? T
  : T extends HostModuleObject
    ? {
        [K in keyof T as T[K] extends HostExportFunction
          ? K
          : T[K] extends HostModuleObject
            ? K
            : never]?: T[K] extends HostExportFunction
          ? T[K]
          : T[K] extends HostModuleObject
            ? RebindHostModule<T[K]>
            : never
      }
    : never

// ─────────────────────────────────────────────────────────────────────────
// Sandbox (runtime)
// ─────────────────────────────────────────────────────────────────────────

export interface SandboxOptions {
  /**
   * Maximum number of runs executing at once. Additional callers queue FIFO
   * until a run finishes; a queued caller's `AbortSignal` is honoured while
   * it waits, so `AbortSignal.timeout()` composes as a queue-wait bound —
   * there is no separate timeout option.
   *
   * This is an admission number, not a socket count: connections to the
   * runtime process open on demand as runs need them and are reused for the
   * process lifetime (`SandboxStats.openConnections` reports the live
   * count). Multiple MCP agents / concurrent callers run in parallel up to
   * this limit.
   *
   * Overridable in both directions: lowering it leaves cores to the host
   * app; raising it above the core count pays only for workloads that spend
   * their time suspended on host calls rather than computing.
   *
   * This caps *concurrent runs* only. How many isolates stay resident
   * (warm instances included) is the memory budget's job — see
   * `memoryBudgetMb`. There is no instance-count cap of any kind, so
   * idle warm instances may outnumber the running count here, or fall below
   * it under memory pressure.
   *
   * Must be an integer ≥ 1 — anything else throws at `createSandbox()`
   * (`0` would queue every run forever).
   *
   * Defaults to `os.availableParallelism()`.
   */
  maxConcurrentRuns?: number

  /**
   * Hard cap on memory each isolate can use, in megabytes. Covers the V8
   * heap and all external `ArrayBuffer` allocations; also determines the
   * BridgeResponse frame read cap (the sandbox cannot receive a response
   * larger than its own memory budget).
   *
   * Uniform across ALL isolates of this Sandbox and settable only here —
   * never per run or per prefix. The cap is baked into the isolate at
   * creation, and prefix runs reuse warm isolates, so a per-run value is
   * structurally impossible; a uniform cap also keeps capacity math simple
   * (slots × cap). Memory accumulates across calls on a warm instance —
   * hitting the cap taints the instance and the next call cold-starts.
   *
   * Zero means no cap.
   * @default 128
   */
  memoryMb?: number

  /**
   * The runtime's memory mark, in megabytes (celld's model, one
   * mark). The runtime watches its own process RSS against it: at/above
   * the mark it evicts idle warm instances by `heapUsed × idleTime` score
   * (highest first) AND stops pooling new instances — prefix runs without
   * an idle instance execute on cold one-off isolates — until RSS falls
   * back to 80 % of the mark (hysteresis, so eviction doesn't flap).
   * Reusing an already-warm instance stays allowed under pressure; it adds
   * no memory. Correctness never depends on warmth; the only observable
   * cost of eviction is cold-start latency. There is no instance-count
   * cap — concurrency is bounded by `maxConcurrentRuns`, memory by this mark.
   *
   * `0` disables the mark entirely (nothing bounds warmth then except
   * `dispose()`). Independent of `memoryMb`: RSS is measured, not derived
   * from per-isolate caps.
   *
   * Default: the memory available to this process — container/cgroup-aware
   * via `process.constrainedMemory()`, falling back to `os.totalmem()` —
   * minus a safety net of max(512 MB, 25 %) for the Node host, the Rust
   * runtime, and whatever the embedding service keeps in memory per isolate.
   * Services with a large per-isolate host cache should set this lower.
   * On a host too small for that subtraction the default floors at 64 MB
   * (with a warning on stderr) rather than reaching 0 and disabling the
   * mark: memory-starved hosts get aggressive eviction, never no protection.
   * The floor applies to the default only — an explicit `0` still opts out.
   * Explicit values are clamped to `Number.MAX_SAFE_INTEGER` bytes (above
   * that the byte math stops being exact) and a negative value to `0`; a
   * non-finite one throws.
   */
  memoryBudgetMb?: number

  /**
   * Override the path to the Rust V8 binary.
   * Default: auto-detect from \@iso4/v8-* platform packages.
   */
  binaryPath?: string
}

/**
 * A point-in-time capacity/usage snapshot from `sandbox.stats()`.
 * The runtime-side numbers are mutually consistent (taken under one
 * registry lock); `queueDepth` is a separate host-side read taken after
 * the round trip. All of it is stale the moment it returns —
 * diagnostics, not synchronization.
 */
export interface SandboxStats {
  /**
   * Isolates executing right now: one-off `run()`s plus prefix runs on warm
   * instances.
   */
  activeRuns: number
  /**
   * Callers queued for a free run slot (`maxConcurrentRuns` runs are
   * already executing).
   */
  queueDepth: number
  /**
   * Host-side count of runtime connections as the pool tracks them (the
   * dedicated `stats()` control connection not included). Runs are
   * multiplexed onto shared connections — several concurrent runs per
   * connection, another opened only when all are at the internal
   * per-connection cap — and connections are kept for the process lifetime,
   * so this rises to roughly the concurrency high-water mark divided by the
   * cap and stays there. Capacity is `maxConcurrentRuns`, an admission
   * number decoupled from sockets. It is a ledger, not a per-read socket
   * probe: a connection that died stays counted until the next run
   * observes and replaces it.
   */
  openConnections: number
  /**
   * Resident warm instances — busy plus idle. Bounded by memory (the RSS
   * mark), not by a count.
   */
  warmInstances: number
  /**
   * Idle warm instances ready to serve their prefix without a cold start.
   */
  idleInstances: number
  /**
   * Summed heap of the idle instances in bytes, each measured after its
   * last call (a busy instance's current heap is unknown mid-call).
   */
  idleHeapBytes: number
  /**
   * The memory mark the runtime sheds against, in bytes —
   * `memoryBudgetMb` as the runtime received it. 0 = watermarks disabled.
   * Utilization is `rssBytes / budgetBytes`.
   */
  budgetBytes: number
  /**
   * The runtime process's resident set size in bytes at snapshot time —
   * the signal the mark acts on. 0 when the platform offers no reader.
   */
  rssBytes: number
  /**
   * True while the runtime is shedding: RSS reached the budget and
   * has not yet fallen back to 80 % of it. While shedding, idle instances
   * are evicted by score and new warm admissions stop (prefix runs without
   * an idle instance degrade to cold one-off isolates).
   */
  underPressure: boolean
  /**
   * Per-prefix instance counts, keyed by prefix id — saturation of a single
   * hot prefix is diagnosable here.
   */
  prefixes: Record<string, { idle: number, busy: number }>
}

export interface Sandbox {
  /**
   * Execute a piece of JavaScript in a fresh V8 isolate.
   * For repeated use with a shared context, prefer prepare() + prefix.execute().
   *
   * With `call`, the freshly evaluated module's export at `call.export` is
   * invoked and the result carries its return `value` instead of `exports`:
   *
   * ```ts
   * await sandbox.run({
   *   code: `export default { async fetch(request) { return new Response('hi') } }`,
   *   call: { export: 'default.fetch', args: [request] },
   * })
   * ```
   */
  run: {
    (options: RunCallOptions): Promise<CallResult>
    (options: RunOptions): Promise<RunResult>
  }

  /**
   * Load a module once and read its serializable exports — the
   * deploy/registration path (IaC-style declaration exports read when a
   * function is created, never per request). Builds no prefix and retains
   * nothing. Function exports are skipped and reported, so a module that
   * also exports handlers reads cleanly. Rejects on compile/runtime errors,
   * like `prepare()`.
   */
  readExports: (options: ReadExportsOptions) => Promise<ReadExportsResult>

  /**
   * Validate and prepare a prefix of code for repeated runs.
   *
   * The type parameter `G` is inferred from the `globals` you pass and flows
   * into the returned `Prefix<G>`. This lets TypeScript enforce at the call
   * site that `prefix.run()` can only rebind names declared here:
   *
   * ```ts
   * const prefix = await sandbox.precompile({
   *   globals: { fetch: myHandler, myTool: otherHandler },
   * })
   * // prefix: Prefix<{ fetch: ..., myTool: ... }>
   *
   * prefix.run({ globals: { fetch: newHandler } })          // ✅
   * prefix.run({ globals: { undeclared: someHandler } })    // ❌ TS error
   * ```
   *
   * Globals declared here serve as **default** implementations for all runs.
   * `prefix.run()` may override any subset; omitted names reuse the default.
   */

  /**
   * eslint-disable \@typescript-eslint/no-empty-object-type
   */
  prepare: <
    G extends HostGlobals = {},
    M extends Imports = {},
  >(
    options: PrecompileOptions<G, M>,
  ) => Promise<Prefix<G, M>>

  /**
   * @deprecated Renamed to {@link Sandbox.prepare}. `precompile` stays as an
   * alias (identical behavior) and is slated for removal in a future major.
   */
  precompile: <
    G extends HostGlobals = {},
    M extends Imports = {},
  >(
    options: PrecompileOptions<G, M>,
  ) => Promise<Prefix<G, M>>

  /**
   * A point-in-time capacity/usage snapshot: active runs, queue
   * depth, warm-instance counts and their measured memory. Served over a
   * dedicated control connection, so it answers even while every run slot
   * is busy. See {@link SandboxStats}.
   */
  stats: () => Promise<SandboxStats>

  /**
   * Tear down the Rust process. Outstanding prefixes are invalidated.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using sandbox = await createSandbox()` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

export type CreateSandbox = (options?: SandboxOptions) => Promise<Sandbox>

// ─────────────────────────────────────────────────────────────────────────
// Precompiled prefix
// ─────────────────────────────────────────────────────────────────────────

/**
 * Options for `sandbox.precompile()`.
 *
 * `G` is the shape of globals this prefix declares. TypeScript infers it
 * from the `globals` field, so the returned `Prefix<G>` is typed to allow
 * only those names to be rebound in subsequent `prefix.run()` calls.
 */
export interface PrecompileOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * ESM prefix source, evaluated at the start of every run. Top-level await works.
   *
   * @example
   *   import { search } from 'tools:search';
   *   globalThis.search = search;
   */
  code: string

  /**
   * Declares the globals that sandbox code will be able to call.
   *
   * This defines the **bridge surface shape** — the full set of names the
   * sandbox may invoke as globals. Names declared here:
   *
   * - Become bridge stubs in the V8 context on every `prefix.run()` call.
   * - Can be rebound per-run via `prefix.run({ globals })`.
   * - Cannot be supplemented at run time — a name not declared here will
   *   cause `ERR_UNDECLARED_BINDING` if passed to `prefix.run()`.
   *
   * The handlers provided here are the **default** implementations reused by
   * any `prefix.run()` call that does not override them.
   */
  globals?: G

  /**
   * Declares the imports the sandbox code may resolve.
   *
   * The inferred shape feeds `Prefix<G, M>` so `prefix.run()` knows which
   * specifiers exist and which exports may be rebound.
   */
  imports?: M

  /**
   * Resource limits applied to prefix code evaluation.
   *
   * **Currently a no-op placeholder.** Pass limits directly to each
   * `prefix.run()` call. The one budget that DOES apply here is not
   * configurable: prefix evaluation runs under the fixed warm-up budget
   * (1 s wall / 1 s CPU) — a prefix that cannot evaluate inside it is
   * rejected with `ERR_WARMUP_LIMIT` at `prepare()` time, because it could
   * never cold-start a warm instance either.
   */
  limits?: ResourceLimits

  /**
   * Optional filename for stack traces. Default: "<prefix>".
   */
  filename?: string
}

/**
 * Handle to a precompiled prefix.
 *
 * `G` is the shape of globals declared at precompile time. `prefix.run()`
 * accepts only `Partial<G>` for its `globals` field — you may override any
 * declared global's implementation per run, but you cannot add names that
 * were not declared at precompile time.
 *
 * **Warm instances.** Runs on a prefix are served by resident
 * isolates: the first run cold-starts one (prefix evaluated once, under the
 * fixed warm-up budget), later runs reuse it and skip isolate boot and
 * prefix re-evaluation. Warmth is a cache, never a guarantee — module-scope
 * state MAY survive between runs on one instance, but any instance can be
 * evicted at any moment (a CPU/memory limit firing mid-execution, an abort
 * landing on running code, memory pressure,
 * `dispose()`), and concurrent runs of one prefix are served by separate
 * instances that share no state. Do not rely on carryover, and do not rely
 * on per-run isolation within a prefix either: keep durable state outside
 * the sandbox, and do per-request setup inside the handler — lazy init
 * (`conn ??= await setup()`) runs under that call's budget and re-runs
 * correctly after any eviction.
 */
export interface Prefix<
  G extends HostGlobals = {},
  M extends Imports = {},
> {
  readonly id: string

  /**
   * Execute dynamic code against this prefix's declared state.
   *
   * Globals declared at precompile time are active. You may rebind any subset
   * of them via `options.globals`; the precompile-time handler is used for
   * any name not overridden here. Same rule for `imports`, restricted to
   * host-import function exports declared in `I`.
   *
   * @example
   *   const result = await prefix.execute({
   *     code: `export default await (${agentFn})()`,
   *   })
   */
  execute: (options: PrefixRunOptions<G, M>) => Promise<RunResult>

  /**
   * @deprecated Renamed to {@link Prefix.execute}. `run` stays as an alias
   * (identical behavior) and is slated for removal in a future major.
   */
  run: (options: PrefixRunOptions<G, M>) => Promise<RunResult>

  /**
   * Call a function exported by this prefix's module — nothing is compiled
   * per request. On a warm instance the prefix is not even re-evaluated:
   * `export` resolves against the retained module and the result carries
   * the function's return value:
   *
   * ```ts
   * const prefix = await sandbox.prepare({ code: bundle })
   * const result = await prefix.call({ export: 'default.fetch', args: [request] })
   * ```
   *
   * `globals` / `imports` rebind per call exactly as they do for
   * {@link Prefix.execute}.
   */
  call: (options: PrefixCallOptions<G, M>) => Promise<CallResult>

  /**
   * Release the prepared prefix. Subsequent run() calls reject. Idempotent.
   */
  dispose: () => Promise<void>

  /**
   * Enables `await using prefix = await sandbox.precompile(...)` syntax.
   */
  [Symbol.asyncDispose]: () => Promise<void>

  readonly alive: boolean
}

/**
 * Options for `prefix.run()`.
 *
 * `G` is the declared-globals shape from the matching `precompile()` call.
 * The `globals` field is typed as `Partial<G>` — only names present in `G`
 * may be overridden. Passing any other name is a TypeScript error at compile
 * time and `ERR_UNDECLARED_BINDING` at runtime.
 */
export interface PrefixRunOptions<
  G extends HostGlobals,
  M extends Imports,
> {
  /**
   * Dynamic ESM source code to compile and run against the prefix state.
   */
  code: string

  /**
   * Override implementations for a **subset** of globals declared at
   * precompile time. Only names present in `G` are accepted (TypeScript
   * error + runtime `ERR_UNDECLARED_BINDING` for anything else), but the
   * function signature does not need to match the precompile-time handler
   * exactly — any `HostExportFunction`-compatible value is accepted.
   */
  globals?: RebindGlobals<G>

  /**
   * Rebind host-module function exports declared at precompile time.
   * Source module imports are frozen at prepare() time and cannot be rebound;
   * data exports are baked into the synthetic module. TypeScript enforces
   * this at the type level via `RebindImports<M>`; the runtime rejects
   * anything that slips through with `ERR_UNDECLARED_BINDING`.
   */
  imports?: RebindImports<M>

  limits?: ResourceLimits
  signal?: AbortSignal
  filename?: string
}

/**
 * Options for `prefix.call()` — a {@link CallTarget} plus the same per-call
 * rebinding surface as {@link PrefixRunOptions}, minus `code`: a call frame
 * carries a postfix *or* a call, never both.
 */
export interface PrefixCallOptions<
  G extends HostGlobals,
  M extends Imports,
> extends CallTarget {
  /**
   * Override implementations for a subset of globals declared at
   * prepare() time — same rules as {@link PrefixRunOptions.globals}.
   */
  globals?: RebindGlobals<G>
  /**
   * Rebind host-module function exports declared at prepare() time — same
   * rules as {@link PrefixRunOptions.imports}.
   */
  imports?: RebindImports<M>
  limits?: ResourceLimits
  signal?: AbortSignal
}

// ─────────────────────────────────────────────────────────────────────────
// Host → sandbox calls
// ─────────────────────────────────────────────────────────────────────────

/**
 * Addresses a function that lives inside the sandbox, **relative to the
 * module's exports** — never `globalThis`. Either a top-level exported
 * function (`"handler"`) or a method on an exported object
 * (`"default.fetch"`).
 *
 * The receiver (`this`) is the object the final path segment was read from —
 * plain `a.b.c()` semantics — so `export default { fetch() { this.… } }` and
 * `export default new Worker()` (prototype methods included) both work.
 * A path that does not resolve, or resolves to something that is not
 * callable, fails the run with `ERR_CALL_TARGET_NOT_FOUND`.
 */
export interface CallTarget {
  /**
   * Dot-separated export path, e.g. `"default.fetch"` or `"handler"`.
   */
  export: string
  /**
   * Arguments for the call. They cross the boundary as **one** V8
   * serialization blob holding the array (identity between arguments
   * preserved), so anything in {@link HostExportData} is accepted — plus
   * `Request` / `Response` / `Headers` at any depth, which arrive in the
   * sandbox as real instances. Defaults to `[]`.
   */
  args?: unknown[]
}

// ─────────────────────────────────────────────────────────────────────────
// Direct run (no prefix)
// ─────────────────────────────────────────────────────────────────────────

export interface RunOptions {
  code: string
  limits?: ResourceLimits
  globals?: HostGlobals
  imports?: Imports
  signal?: AbortSignal
  filename?: string
}

/**
 * `run()` options with a call: the module is evaluated, then
 * `call.export` is resolved against its freshly evaluated exports and
 * invoked. The result carries the function's return {@link CallSuccess.value}
 * instead of `exports` — never both.
 */
export interface RunCallOptions extends RunOptions {
  call: CallTarget
}

/**
 * Options for `sandbox.readExports()` — the deploy/registration path: load a
 * module once and read its declaration exports (IaC-style limits, connection
 * requirements, …). Function-valued exports are absent and reported in
 * {@link ReadExportsResult.skippedExports}, so reading the declarations of a
 * module that also exports handlers is not an error.
 */
export interface ReadExportsOptions {
  code: string
  limits?: ResourceLimits
  filename?: string
}

/**
 * What `sandbox.readExports()` resolves to. Unlike `run()`, failures reject
 * the returned promise (like `prepare()`), since the deploy path treats a
 * broken module as exceptional rather than as a result variant.
 */
export interface ReadExportsResult {
  exports: SandboxExports
  /**
   * Export names absent from `exports` because their value cannot cross the
   * boundary — see {@link RunSuccess.skippedExports}.
   */
  skippedExports: string[]
}

// ─────────────────────────────────────────────────────────────────────────
// Result
// ─────────────────────────────────────────────────────────────────────────

/**
 * Why a run was aborted — whatever value was passed to the aborting
 * `AbortController.abort(reason)` (or left `undefined`). Opaque to iso4 and
 * surfaced verbatim on {@link RunAborted.reason}; a consumer built on top
 * (e.g. a durable-workflow kernel expressing "suspend") gives it meaning.
 */
export type AbortReason = unknown

export type RunResult = RunSuccess | RunFailure | RunAborted

/**
 * Result of a run that carried a {@link CallTarget}: on success the called
 * function's return value replaces `exports` — never both. Failures and
 * aborts are shared with {@link RunResult}.
 */
export type CallResult = CallSuccess | RunFailure | RunAborted

/**
 * The success arm of a {@link CallResult}. Logs, timings, and bridge records
 * are identical to {@link RunSuccess}; only the value slot differs.
 */
export interface CallSuccess {
  status: 'completed'
  ok: true
  /**
   * The called function's return value — awaited first when the function
   * returned a Promise. Anything V8's serialization format carries arrives
   * as a real instance, including a `Response`.
   */
  value: unknown
  stdout: string[]
  stderr: string[]
  durationMs: number
  cpuTimeMs: number
  bridgeCalls: BridgeCallEntry[]
  /**
   * `used_heap_size` of the isolate that served this call, measured after
   * the call settled. Reported for prefix calls (warm instances);
   * `undefined` for one-off `sandbox.run({ call })`.
   */
  heapUsedBytes?: number
  /**
   * Present when the call registered background work with `waitUntil` —
   * see {@link RunSuccess.waitUntil}. Never rejects.
   */
  waitUntil?: Promise<WaitUntilResult>
}

/**
 * Metadata for a single bridge call attempt, recorded by the Rust runtime on
 * the run's own clock. No payloads — names, timing, and sizes only — so
 * recording is cheap enough to stay always-on. Unbounded: every attempt gets
 * an entry (~100 bytes); consumers that only care about a subset filter the
 * list themselves.
 */
export interface BridgeCallEntry {
  /**
   * The name sandbox code called. Plain globals appear as-is (`fetch`),
   * shimmed globals under their public name (not the private stub), and
   * host-module import leaves as `<specifier>.<path>` (e.g.
   * `tools:search.query`).
   */
  name: string
  /**
   * Offset from run start to the attempt, in milliseconds — same clock as
   * the result's `durationMs`, so entries line up on a run timeline.
   */
  startMs: number
  /**
   * Round-trip time the sandbox waited for the response (host handler + IPC),
   * in milliseconds. For calls still unanswered when the run ended
   * (timeout/abort): the time until the run ended. `0` for blocked attempts.
   */
  durationMs: number
  /**
   * Serialized size of the call payload (callId + target + arguments) in
   * bytes — the same size `maxBridgeCallBytes` is enforced against. `0` for
   * attempts blocked before argument serialization.
   */
  argBytes: number
  /**
   * Serialized size of the successful response value in bytes. `0` when the
   * handler failed or the call never settled.
   */
  responseBytes: number
  /**
   * `true` when the host handler resolved and its response reached the
   * sandbox. `false` for handler errors, blocked attempts, and calls still
   * in flight when the run ended.
   */
  ok: boolean
  /**
   * `true` when the attempt was blocked inside the runtime (`maxBridgeCalls`
   * exceeded, payload over `maxBridgeCallBytes`, function argument) and never
   * reached the host.
   */
  blocked: boolean
}

/**
 * Outcome of a run's `waitUntil` grace phase, delivered through
 * {@link RunSuccess.waitUntil} / {@link CallSuccess.waitUntil}. The promise
 * always **resolves** (never rejects), so ignoring it — the intended common
 * case — produces no unhandled-rejection noise.
 */
export interface WaitUntilResult {
  /**
   * `settled`: every registered promise finished within the grace budget.
   * `truncated`: the budget (or a host abort) cut the work short.
   * `failed`: at least one registered promise rejected — a normal outcome,
   * the code finished via its error path; the rest were still driven.
   */
  status: 'settled' | 'truncated' | 'failed'
  /**
   * Wall time of the grace phase (after the result shipped), ms.
   */
  durationMs: number
  /**
   * Active V8 execution time during the grace phase, ms.
   */
  cpuTimeMs: number
  /**
   * Console lines written during the grace phase — the run's own lines
   * arrived on the result itself.
   */
  stdout: string[]
  stderr: string[]
  /**
   * Bridge calls attempted during the grace phase.
   */
  bridgeCalls: BridgeCallEntry[]
  /**
   * The first rejection when `status === 'failed'`, or the fatal error that
   * ended a truncated phase, when one exists.
   */
  error?: { name: string, message: string }
}

/**
 * `status` is the primary discriminant across all three outcomes; `ok` is kept
 * as a convenience alias for `status === 'completed'`, so the common guard
 * stays `if (result.ok)`. Reach for `switch (result.status)` when a deliberate
 * abort must be told apart from a genuine failure.
 */
export interface RunSuccess {
  status: 'completed'
  ok: true
  exports: SandboxExports
  /**
   * Export names absent from `exports` because their value cannot cross the
   * boundary — a function (`export default { fetch }`), a Promise, or a value
   * whose serialization failed. Skipping is never fatal; the names are
   * reported here so nothing is silently hidden.
   *
   * A Promise is skipped **whatever its state**: the export path never awaits,
   * so `export default Promise.resolve(42)` is dropped exactly like a pending
   * one. Export the value instead — `export default await something()` — which
   * works because the module's own evaluation settles before the runtime reads
   * the namespace. `prefix.call()` is the opposite: it awaits a returned
   * Promise and resolves to its value.
   */
  skippedExports: string[]
  /**
   * Lines this run wrote to `console.log` / `.debug` / `.info`, capped by
   * `limits.maxStdoutBytes`. Prefix code shares the same console: when a run
   * cold-starts a warm instance, what the prefix logged while evaluating
   * arrives here once, on that run's result, ahead of the run's own lines.
   */
  stdout: string[]
  /**
   * Same as {@link RunSuccess.stdout}, for `console.warn` / `.error`.
   */
  stderr: string[]
  /**
   * Wall-clock time of the run (start of execution to result), measured in
   * the runtime. Milliseconds with microsecond resolution.
   */
  durationMs: number
  /**
   * Active V8 execution time — time spent waiting on host bridge calls is
   * excluded. Milliseconds with microsecond resolution. The remainder
   * (`durationMs - cpuTimeMs`) is bridge waits plus scheduling.
   */
  cpuTimeMs: number
  /**
   * One entry per bridge call the sandbox attempted, in attempt order —
   * including attempts blocked by limits ({@link BridgeCallEntry.blocked}).
   * Recorded by the Rust runtime.
   */
  bridgeCalls: BridgeCallEntry[]
  /**
   * `used_heap_size` of the isolate that served this run, measured after the
   * run settled. Reported for prefix runs — warm instances keep their
   * heap between calls, and this number feeds eviction. `undefined` for
   * one-off `sandbox.run()` runs, whose isolate is disposed with the run.
   */
  heapUsedBytes?: number
  /**
   * Present when the run registered background work with `waitUntil`:
   * the value in this result was delivered early, the work keeps running
   * runtime-side, and this promise resolves with the grace phase's outcome
   * once it ends. `undefined` for every run that registered nothing. Safe to
   * ignore — it never rejects.
   */
  waitUntil?: Promise<WaitUntilResult>
}

export interface RunFailure {
  status: 'failed'
  ok: false
  error: RunError
  stdout: string[]
  stderr: string[]
  durationMs: number
  cpuTimeMs: number
  bridgeCalls: BridgeCallEntry[]
  /**
   * `used_heap_size` of the isolate that served this run, measured after the
   * run settled. Reported for prefix runs — warm instances keep their
   * heap between calls, and this number feeds eviction. `undefined` for
   * one-off `sandbox.run()` runs, whose isolate is disposed with the run.
   */
  heapUsedBytes?: number
}

/**
 * The run was stopped by an abort — a pre-aborted or mid-run `signal` passed to
 * `run()`, or a host handler that aborted the run. A deliberate outcome, not a
 * crash: `error` is retained (its `code` is always `ERR_ABORTED`) so existing
 * `!result.ok` / `error.code` checks keep working, and `reason` carries the
 * value handed to `abort(reason)`.
 */
export interface RunAborted {
  status: 'aborted'
  ok: false
  error: RunError
  reason?: AbortReason
  stdout: string[]
  stderr: string[]
  durationMs: number
  cpuTimeMs: number
  /**
   * Bridge calls recorded before the abort landed. Populated when the runtime
   * terminates gracefully — the common case, where the run was suspended
   * awaiting a bridge response. Empty (and `durationMs`/`cpuTimeMs` zero) only
   * when graceful termination falls back to socket teardown — e.g. a run
   * aborted while stuck in a tight synchronous loop, or a signal already
   * aborted at run entry.
   */
  bridgeCalls: BridgeCallEntry[]
}

export type SandboxExports = {
  /**
   * Value of `export default` in user code, or `undefined`.
   */
  default: unknown
} & {
  /**
   * Named exports live directly on the export object.
   */
  [name: string]: unknown
}

export interface RunError {
  code: RunErrorCode
  name: string
  message: string
  /**
   * Stack trace of the thrown error. `name`/`message`/`stack` are reserved:
   * they are always read from the error's dedicated properties and never
   * appear inside `fields`, so a thrown object cannot spoof them there.
   */
  stack?: string
  /**
   * All other own enumerable properties of the thrown error (everything
   * except name/message/stack), e.g. `status`, `reason`, or a `data` payload
   * from a custom error class — nested here so nothing can collide with
   * `code`. Present for ERR_USER_CODE and ERR_HOST_BRIDGE when the thrown
   * value is an object with serializable own properties.
   */
  fields?: Record<string, unknown>
  /**
   * Present only for `ERR_INSTANCE_RESET`: what interrupted the co-resident
   * run that took the shared instance down with it.
   */
  resetCause?: ResetCause
  /**
   * Present only for `ERR_INSTANCE_RESET`: the wire run id of the run whose
   * interruption reset the instance — an opaque number, but stable across
   * the victims of one reset, so they can be correlated.
   */
  culpritRunId?: number
}

/**
 * Why a shared instance was reset under an innocent victim — see
 * `RunError.resetCause`.
 */
export type ResetCause = 'cpu' | 'memory' | 'wall' | 'abort' | 'internal'

export type RunErrorCode
  = | 'ERR_USER_CODE'
    | 'ERR_MEMORY_LIMIT'
    | 'ERR_CPU_TIMEOUT'
    | 'ERR_WALL_TIMEOUT'
    | 'ERR_ABORTED'
    | 'ERR_MODULE_NOT_FOUND'
    | 'ERR_COMPILE'
    | 'ERR_FUNCTION_ARGUMENT_NOT_SUPPORTED'
    | 'ERR_EXPORT_NOT_SERIALIZABLE'
    /**
     * A registered host type (`Request`, `Response`, …) cannot cross this
     * boundary in this position — an unimplemented tag, or content that is not
     * self-contained such as a stream body. See `docs/protocol.md` §4.4.5.
     */
    | 'ERR_TYPE_NOT_SERIALIZABLE'
    | 'ERR_EXPORT_TOO_LARGE'
    /**
     * A `call.export` path did not resolve against the module's exports, or
     * resolved to a value that is not callable. The message says which and
     * names the path.
     */
    | 'ERR_CALL_TARGET_NOT_FOUND'
    | 'ERR_HOST_BRIDGE'
    | 'ERR_BRIDGE_PAYLOAD_TOO_LARGE'
    | 'ERR_BRIDGE_CALL_LIMIT_EXCEEDED'
    /**
     * This run was an innocent victim: a co-resident run on the same shared
     * instance was interrupted mid-execution (CPU/memory guard or a forced
     * abort), so the instance could no longer be trusted and every run in
     * flight on it failed. Carries `resetCause` and `culpritRunId`; the
     * telemetry fields are this run's real partial values. Never retried
     * automatically — the victim may have had side effects.
     */
    | 'ERR_INSTANCE_RESET'
    | 'ERR_UNDECLARED_BINDING'
    /**
     * Prefix top-level evaluation never settled — nothing in the isolate
     * can resolve the awaited promise while a prefix evaluates (at
     * `prepare()` validation or at a run's prefix stage).
     */
    | 'ERR_PREFIX_DID_NOT_SETTLE'
    /**
     * Prefix code called a bridge callable (bridge global, shim global, or
     * host-import function). The bridge does not exist while a prefix
     * evaluates, so bridge calls in a prefix are not supported (yet) — do
     * the call in `run()` code instead.
     */
    | 'ERR_PREFIX_BRIDGE_CALL'
    /**
     * Warm-up (prefix evaluation + per-instance runtime installs) exceeded its fixed budget
     * (1 s wall / 1 s CPU — not configurable; Cloudflare's script-startup
     * model). Enforced at `prepare()` and again at every instance
     * cold-start. Move expensive setup into the handler: lazy init on first
     * call runs under that call's budget and survives warm reuse.
     */
    | 'ERR_WARMUP_LIMIT'
    | 'ERR_PREFIX_DISPOSED'
    /**
     * The runtime answered with a `Result` belonging to a different run, or
     * sent a frame that has no place in the run protocol. Host-detected, never
     * reported by the runtime: the two sides lost frame alignment on that
     * connection, so **this run never executed** — nothing ran, nothing was
     * observed, and the telemetry fields are zero rather than partial.
     *
     * The connection is destroyed and replaced before the result is returned,
     * so a retry runs on a fresh one. Seeing this at all is a bug worth
     * reporting; it should be unreachable.
     */
    | 'ERR_PROTOCOL_DESYNC'
    | 'ERR_INTERNAL'
