/**
 * Generated by tsnapi — public API snapshot of `@iso4/sandbox`
 */
// #region Interfaces
export interface BridgeCallEntry {
  name: string;
  startMs: number;
  durationMs: number;
  argBytes: number;
  responseBytes: number;
  ok: boolean;
  blocked: boolean;
}
export interface BridgeGlobal<H extends HostExportFunction = HostExportFunction> extends GlobalOptions {
  kind: "bridge";
  handler: H;
}
export interface BridgeWithShim<H extends (...args: unknown[]) => unknown = (...args: unknown[]) => unknown> extends GlobalOptions {
  kind: "bridge-with-shim";
  handler: H;
  shim: string;
}
export interface CallSuccess {
  status: "completed";
  ok: true;
  value: unknown;
  stdout: string[];
  stderr: string[];
  durationMs: number;
  cpuTimeMs: number;
  bridgeCalls: BridgeCallEntry[];
  heapUsedBytes?: number;
  waitUntil?: Promise<WaitUntilResult>;
}
export interface CallTarget {
  export: string;
  args?: unknown[];
}
export interface DataGlobal extends GlobalOptions {
  kind: "data";
  value: HostExportData | Request | Response | Headers;
}
export interface GlobalOptions {
  enumerable?: boolean;
}
export interface HostModuleObject {
  [name: string]: HostModuleValue;
}
export interface PrecompileOptions<G extends HostGlobals, M extends Imports> {
  code: string;
  globals?: G;
  imports?: M;
  limits?: ResourceLimits;
  filename?: string;
}
export interface Prefix<G extends HostGlobals = {}, M extends Imports = {}> {
  readonly id: string;
  execute: (_: PrefixRunOptions<G, M>) => Promise<RunResult>;
  run: (_: PrefixRunOptions<G, M>) => Promise<RunResult>;
  call: (_: PrefixCallOptions<G, M>) => Promise<CallResult>;
  dispose: () => Promise<void>;
  [Symbol.asyncDispose]: () => Promise<void>;
  readonly alive: boolean;
}
export interface PrefixCallOptions<G extends HostGlobals, M extends Imports> extends CallTarget {
  globals?: RebindGlobals<G>;
  imports?: RebindImports<M>;
  limits?: ResourceLimits;
  signal?: AbortSignal;
}
export interface PrefixRunOptions<G extends HostGlobals, M extends Imports> {
  code: string;
  globals?: RebindGlobals<G>;
  imports?: RebindImports<M>;
  limits?: ResourceLimits;
  signal?: AbortSignal;
  filename?: string;
}
export interface ReadExportsOptions {
  code: string;
  limits?: ResourceLimits;
  filename?: string;
}
export interface ReadExportsResult {
  exports: SandboxExports;
  skippedExports: string[];
}
export interface ResourceLimits {
  cpuTimeMs?: number;
  wallTimeMs?: number;
  maxBridgeCallBytes?: number;
  maxExportBytes?: number;
  maxStdoutBytes?: number;
  maxStderrBytes?: number;
  maxBridgeCalls?: number;
  graceMs?: number;
}
export interface RunCallOptions extends RunOptions {
  call: CallTarget;
}
export interface RunError {
  code: RunErrorCode;
  name: string;
  message: string;
  stack?: string;
  fields?: Record<string, unknown>;
  resetCause?: ResetCause;
  culpritRunId?: number;
}
export interface RunFailure {
  status: "failed";
  ok: false;
  error: RunError;
  stdout: string[];
  stderr: string[];
  durationMs: number;
  cpuTimeMs: number;
  bridgeCalls: BridgeCallEntry[];
  heapUsedBytes?: number;
}
export interface RunOptions {
  code: string;
  limits?: ResourceLimits;
  globals?: HostGlobals;
  imports?: Imports;
  signal?: AbortSignal;
  filename?: string;
}
export interface RunSuccess {
  status: "completed";
  ok: true;
  exports: SandboxExports;
  skippedExports: string[];
  stdout: string[];
  stderr: string[];
  durationMs: number;
  cpuTimeMs: number;
  bridgeCalls: BridgeCallEntry[];
  heapUsedBytes?: number;
  waitUntil?: Promise<WaitUntilResult>;
}
export interface Sandbox {
  run: {
    (_: RunCallOptions): Promise<CallResult>;
    (_: RunOptions): Promise<RunResult>;
  };
  readExports: (_: ReadExportsOptions) => Promise<ReadExportsResult>;
  prepare: <G extends HostGlobals = {}, M extends Imports = {}>(_: PrecompileOptions<G, M>) => Promise<Prefix<G, M>>;
  precompile: <G extends HostGlobals = {}, M extends Imports = {}>(_: PrecompileOptions<G, M>) => Promise<Prefix<G, M>>;
  stats: () => Promise<SandboxStats>;
  dispose: () => Promise<void>;
  [Symbol.asyncDispose]: () => Promise<void>;
  readonly alive: boolean;
}
export interface SandboxOptions {
  maxIsolates?: number;
  memoryMb?: number;
  memoryBudgetMb?: number;
  binaryPath?: string;
}
export interface SandboxStats {
  activeRuns: number;
  queueDepth: number;
  warmInstances: number;
  idleInstances: number;
  idleHeapBytes: number;
  budgetBytes: number;
  rssBytes: number;
  underPressure: boolean;
  prefixes: Record<string, {
    idle: number;
    busy: number;
  }>;
}
export interface StringGlobal extends GlobalOptions {
  kind: "string";
  expr: string;
}
export interface WaitUntilResult {
  status: "settled" | "truncated" | "failed";
  durationMs: number;
  cpuTimeMs: number;
  stdout: string[];
  stderr: string[];
  bridgeCalls: BridgeCallEntry[];
  error?: {
    name: string;
    message: string;
  };
}
// #endregion

// #region Types
export type CallResult = CallSuccess | RunFailure | RunAborted;
export type CreateSandbox = (_?: SandboxOptions) => Promise<Sandbox>;
export type HostExportData = null | undefined | boolean | number | bigint | string | Date | RegExp | Error | Map<HostExportData, HostExportData> | Set<HostExportData> | ArrayBuffer | DataView | Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array | Float32Array | Float64Array | BigInt64Array | BigUint64Array | HostExportData[] | {
  [key: string]: HostExportData;
};
export type HostExportFunction = (..._: unknown[]) => unknown;
export type HostGlobals = Record<string, HostGlobalValue>;
export type HostGlobalValue = HostExportFunction | string | BridgeWithShim<any> | DataGlobal | BridgeGlobal<any> | StringGlobal;
export type HostModuleValue = HostExportFunction | HostExportData | HostModuleObject;
export type Imports<M extends Record<string, ImportValue> = Record<string, ImportValue>> = M;
export type ImportValue = string | HostModuleObject;
export type RebindGlobals<G extends HostGlobals> = { [K in keyof G as G[K] extends string | DataGlobal | StringGlobal ? never : K]?: RebindValue<G[K]> };
export type RebindHostModule<T> = T extends HostExportFunction ? T : T extends HostModuleObject ? { [K in keyof T as T[K] extends HostExportFunction ? K : T[K] extends HostModuleObject ? K : never]?: T[K] extends HostExportFunction ? T[K] : T[K] extends HostModuleObject ? RebindHostModule<T[K]> : never } : never;
export type RebindImports<M extends Record<string, ImportValue>> = Record<string, ImportValue> extends M ? Record<string, never> : { [K in keyof M as M[K] extends string ? never : K]?: M[K] extends HostModuleObject ? RebindHostModule<M[K]> : never };
export type RebindValue<V extends HostGlobalValue> = V extends BridgeWithShim<infer H> ? H : V extends BridgeGlobal<infer H> ? H : V extends HostExportFunction ? V : never;
export type ResetCause = "cpu" | "memory" | "wall" | "abort" | "internal";
export type RunErrorCode = "ERR_USER_CODE" | "ERR_MEMORY_LIMIT" | "ERR_CPU_TIMEOUT" | "ERR_WALL_TIMEOUT" | "ERR_ABORTED" | "ERR_MODULE_NOT_FOUND" | "ERR_COMPILE" | "ERR_FUNCTION_ARGUMENT_NOT_SUPPORTED" | "ERR_EXPORT_NOT_SERIALIZABLE" | "ERR_TYPE_NOT_SERIALIZABLE" | "ERR_EXPORT_TOO_LARGE" | "ERR_CALL_TARGET_NOT_FOUND" | "ERR_HOST_BRIDGE" | "ERR_BRIDGE_PAYLOAD_TOO_LARGE" | "ERR_BRIDGE_CALL_LIMIT_EXCEEDED" | "ERR_INSTANCE_RESET" | "ERR_UNDECLARED_BINDING" | "ERR_PREFIX_DID_NOT_SETTLE" | "ERR_PREFIX_BRIDGE_CALL" | "ERR_WARMUP_LIMIT" | "ERR_PREFIX_DISPOSED" | "ERR_PROTOCOL_DESYNC" | "ERR_INTERNAL";
export type RunResult = RunSuccess | RunFailure | RunAborted;
export type SandboxExports = {
  default: unknown;
} & {
  [name: string]: unknown;
};
// #endregion

// #region Functions
export declare function createSandbox(_?: SandboxOptions): Promise<Sandbox>;
// #endregion