/**
 * Generated by tsnapi — public API snapshot of `@iso4/fetch`
 */
// #region Interfaces
export interface FetchContext {
  readonly req: FetchContextReq;
  res: HostFetchResponse | null;
}
export interface FetchContextReq {
  readonly url: string;
  readonly method: string;
  readonly params: Record<string, string>;
  readonly hop: number;
  readonly raw: HostFetchRequest;
  headers: Record<string, string>;
  body: Uint8Array | string | null;
  header: (_: string, _: string) => void;
  setUrl: (_: string) => void;
  setBody: (_: Uint8Array | string | null) => void;
}
export interface FetchOriginRule {
  host: string | string[];
  port?: number | number[];
  httpsOnly?: boolean;
  routes: FetchRouteRule[];
  middleware?: FetchMiddleware;
}
export interface FetchRouteRule {
  path: string;
  methods?: string | string[];
  middleware?: FetchMiddleware;
}
export interface HostFetchRequest {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: Uint8Array | string | null;
  signal?: AbortSignal;
}
export interface HostFetchResponse {
  status: number;
  statusText?: string;
  headers: Record<string, string>;
  body: unknown;
}
export interface SafeFetchGlobal {
  kind: "bridge-with-shim";
  handler: SafeFetchFn;
  shim: string;
}
export interface SafeFetchOptions {
  rules?: FetchOriginRule | FetchOriginRule[];
  policy?: SafeFetchPolicy;
  middleware?: FetchMiddleware;
  pinDns?: boolean;
  maxRedirects?: number;
  timeoutMs?: number;
  maxBodyBytes?: number;
  allowCompressedResponses?: boolean;
  onDenied?: (_: SafeFetchRequest, _: string) => void | Promise<void>;
}
export interface SafeFetchRequest {
  url: string;
  protocol: "http" | "https";
  host: string;
  port: number;
  path: string;
  method: string;
  headers: Record<string, string>;
  resolvedIp: string | null;
  hop: number;
}
// #endregion

// #region Types
export type FetchMiddleware = (_: FetchContext, _: Next) => HostFetchResponse | void | Promise<HostFetchResponse | void>;
export type Next = () => Promise<void>;
export type SafeFetchFn = (..._: unknown[]) => Promise<HostFetchResponse>;
export type SafeFetchPolicy = (_: SafeFetchRequest) => boolean | Promise<boolean>;
// #endregion

// #region Functions
export declare function createSafeFetch(_: SafeFetchOptions): SafeFetchGlobal;
// #endregion